import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "Finanzkennzahlen",
  metrics: {
    priceToEarningsRatio: ["KGV", "Vergleicht den Aktienkurs mit dem Gewinn je Aktie und zeigt, wie hoch der Markt die aktuellen Gewinne bewertet."],
    priceToEarningsGrowthRatio: ["PEG-Ratio", "Setzt das KGV ins Verhältnis zum erwarteten Gewinnwachstum; ein niedrigerer Wert kann auf eine günstigere Wachstumsbewertung hindeuten."],
    returnOnEquity: ["Eigenkapitalrendite", "Zeigt, wie effizient das Unternehmen mit dem Eigenkapital Gewinn erzielt."],
    returnOnInvestedCapital: ["Rendite auf investiertes Kapital", "Zeigt, wie wirksam das Unternehmen das investierte Kapital verzinst."],
    netProfitMargin: ["Nettogewinnmarge", "Anteil des Umsatzes, der nach allen Kosten, Zinsen und Steuern als Nettogewinn bleibt."],
    freeCashFlowYield: ["Free-Cashflow-Rendite", "Vergleicht den freien Cashflow mit dem Marktwert und zeigt die verfügbare Cash-Rendite."],
    debtToEquityRatio: ["Verschuldungsgrad", "Vergleicht die Schulden mit dem Eigenkapital; ein höherer Wert bedeutet meist mehr finanzielle Hebelwirkung."],
    currentRatio: ["Liquidität 3. Grades", "Vergleicht das Umlaufvermögen mit den kurzfristigen Verbindlichkeiten."],
    forwardPE: ["Erwartetes KGV", "Vergleicht den Aktienkurs mit dem prognostizierten Gewinn des nächsten Geschäftsjahres."],
    priceToSalesRatio: ["KUV", "Vergleicht den Börsenwert des Unternehmens mit seinem Umsatz."],
    priceToBookRatio: ["KBV", "Vergleicht den Aktienkurs mit dem Buchwert je Aktie."],
    priceToFreeCashFlowRatio: ["Kurs / Free Cashflow", "Vergleicht den Marktwert mit dem freien Cashflow statt mit dem Bilanzgewinn."],
    priceToOperatingCashFlowRatio: ["Kurs / operativer Cashflow", "Vergleicht den Marktwert mit dem Cashflow aus dem operativen Geschäft."],
    enterpriseValueMultiple: ["EV/EBITDA", "Vergleicht den Unternehmenswert mit dem EBITDA und macht Bewertungen unabhängig von Finanzierung und Abschreibungen besser vergleichbar."],
    priceToFairValue: ["Kurs / fairer Wert", "Vergleicht den aktuellen Aktienkurs mit einem geschätzten fundamentalen fairen Wert."],
    returnOnAssets: ["Gesamtkapitalrendite", "Zeigt, wie effizient das Unternehmen seine Vermögenswerte zur Gewinnerzielung nutzt."],
    returnOnCapitalEmployed: ["ROCE", "Zeigt, wie effizient operativer Gewinn aus Eigen- und Fremdkapital erzielt wird."],
    grossProfitMargin: ["Bruttomarge", "Anteil des Umsatzes, der nach direkten Herstellungskosten übrig bleibt."],
    operatingProfitMargin: ["Operative Marge", "Anteil des Umsatzes, der nach operativen Aufwendungen als operativer Gewinn bleibt."],
    ebitdaMargin: ["EBITDA-Marge", "EBITDA in Prozent des Umsatzes, vor Zinsen, Steuern und Abschreibungen."],
    ebitMargin: ["EBIT-Marge", "Ergebnis vor Zinsen und Steuern in Prozent des Umsatzes."],
    pretaxProfitMargin: ["Vorsteuermarge", "Gewinn vor Steuern in Prozent des Umsatzes."],
    freeCashFlowMargin: ["Free-Cashflow-Marge", "Freier Cashflow in Prozent des Umsatzes nach Investitionen."],
    bottomLineProfitMargin: ["Endgültige Nettomarge", "Nettogewinn in Prozent des Umsatzes nach allen Kosten und Steuern."],
    continuousOperationsProfitMargin: ["Marge fortgeführter Aktivitäten", "Profitabilität des laufenden Geschäfts ohne aufgegebene Geschäftsbereiche."],
    freeCashFlowPerShare: ["Free Cashflow je Aktie", "Freier Cashflow geteilt durch die ausstehenden Aktien."],
    revenuePerShare: ["Umsatz je Aktie", "Umsatz geteilt durch die ausstehenden Aktien."],
    netIncomePerShare: ["Nettogewinn je Aktie", "Nettogewinn, der auf eine ausstehende Stammaktie entfällt."],
    operatingCashFlowPerShare: ["Operativer Cashflow je Aktie", "Cashflow aus dem operativen Geschäft geteilt durch die ausstehenden Aktien."],
    bookValuePerShare: ["Buchwert je Aktie", "Eigenkapital geteilt durch die ausstehenden Aktien."],
    tangibleBookValuePerShare: ["Materieller Buchwert je Aktie", "Buchwert je Aktie ohne Goodwill und andere immaterielle Vermögenswerte."],
    cashPerShare: ["Barmittel je Aktie", "Barmittel und Zahlungsmitteläquivalente geteilt durch die ausstehenden Aktien."],
    shareholdersEquityPerShare: ["Eigenkapital je Aktie", "Den Anteilseignern zurechenbares Eigenkapital geteilt durch die ausstehenden Aktien."],
    interestDebtPerShare: ["Verzinsliche Schulden je Aktie", "Verzinsliche Schulden geteilt durch die ausstehenden Aktien."],
    capexPerShare: ["Investitionen je Aktie", "Investitionsausgaben geteilt durch die ausstehenden Aktien."],
    dividendYield: ["Dividendenrendite", "Jährliche Dividende je Aktie im Verhältnis zum Aktienkurs."],
    dividendPerShare: ["Dividende je Aktie", "Gezahlte Dividenden geteilt durch die ausstehenden Aktien."],
    dividendPayoutRatio: ["Ausschüttungsquote", "Anteil des Gewinns, der als Dividende an die Aktionäre ausgeschüttet wird."],
    dividendYieldPercentage: ["Dividendenrendite %", "Jährliche Dividende im Verhältnis zum Aktienkurs, ausgedrückt in Prozent."],
    quickRatio: ["Liquidität 2. Grades", "Vergleicht schnell verfügbare Vermögenswerte ohne Vorräte mit den kurzfristigen Verbindlichkeiten."],
    cashRatio: ["Liquidität 1. Grades", "Vergleicht Barmittel und Zahlungsmitteläquivalente mit den kurzfristigen Verbindlichkeiten."],
    debtToAssetsRatio: ["Schuldenquote", "Anteil der Vermögenswerte, der durch Schulden finanziert ist."],
    debtToCapitalRatio: ["Schulden / Gesamtkapital", "Vergleicht die Schulden mit dem Gesamtkapital aus Schulden und Eigenkapital."],
    longTermDebtToCapitalRatio: ["Langfristschulden / Kapital", "Anteil des Gesamtkapitals, der mit langfristigen Schulden finanziert ist."],
    debtToMarketCap: ["Schulden / Börsenwert", "Vergleicht die Gesamtschulden mit dem Börsenwert des Unternehmens."],
    financialLeverageRatio: ["Finanzieller Hebel", "Zeigt, wie stark das Unternehmen zur Finanzierung seiner Vermögenswerte auf Schulden setzt."],
    solvencyRatio: ["Solvabilitätsquote", "Zeigt die Fähigkeit, langfristige finanzielle Verpflichtungen zu erfüllen."],
    interestCoverageRatio: ["Zinsdeckungsgrad", "Zeigt, wie oft der operative Gewinn den Zinsaufwand deckt."],
    operatingCashFlowRatio: ["Operativer Cashflow / kurzfristige Schulden", "Zeigt, wie gut der operative Cashflow kurzfristige Verbindlichkeiten deckt."],
    operatingCashFlowSalesRatio: ["Operativer Cashflow / Umsatz", "Zeigt, wie effizient Umsatz in operativen Cashflow umgewandelt wird."],
    freeCashFlowOperatingCashFlowRatio: ["Free Cashflow / operativer Cashflow", "Anteil des operativen Cashflows, der nach Investitionen als freier Cashflow bleibt."],
    debtServiceCoverageRatio: ["Schuldendienstdeckungsgrad", "Zeigt, wie gut das operative Ergebnis Zins- und Tilgungszahlungen deckt."],
    operatingCashFlowCoverageRatio: ["Cashflow-Deckungsgrad", "Zeigt, wie gut der operative Cashflow die gesamten Schuldenverpflichtungen deckt."],
    capitalExpenditureCoverageRatio: ["Investitionsdeckungsgrad", "Zeigt, wie gut der operative Cashflow die Investitionsausgaben deckt."],
    dividendPaidAndCapexCoverageRatio: ["Dividenden- und Investitionsdeckung", "Zeigt, wie gut der operative Cashflow Dividenden und Investitionen zusammen deckt."],
    shortTermOperatingCashFlowCoverageRatio: ["Kurzfristige Cashflow-Deckung", "Zeigt, wie gut der operative Cashflow kurzfristige Verpflichtungen deckt."],
    assetTurnover: ["Kapitalumschlag", "Zeigt, wie effizient Vermögenswerte zur Umsatzerzielung eingesetzt werden."],
    inventoryTurnover: ["Lagerumschlag", "Zeigt, wie oft Vorräte in einer Periode verkauft und ersetzt werden."],
    receivablesTurnover: ["Forderungsumschlag", "Zeigt, wie effizient das Unternehmen Forderungen aus Kreditverkäufen einzieht."],
    payablesTurnover: ["Verbindlichkeitenumschlag", "Zeigt, wie schnell das Unternehmen seine Lieferanten bezahlt."],
    fixedAssetTurnover: ["Anlagevermögensumschlag", "Zeigt, wie effizient Anlagevermögen zur Umsatzerzielung eingesetzt wird."],
    workingCapitalTurnoverRatio: ["Working-Capital-Umschlag", "Zeigt, wie effizient das Working Capital zur Umsatzerzielung eingesetzt wird."],
    effectiveTaxRate: ["Effektiver Steuersatz", "Durchschnittlicher Steuersatz auf den Gewinn vor Steuern."],
    netIncomePerEBT: ["Nettogewinn / EBT", "Anteil des Vorsteuergewinns, der nach Steuern als Nettogewinn bleibt."],
    ebtPerEbit: ["EBT / EBIT", "Zeigt den Einfluss von Zinsen und nicht operativen Posten auf das operative Ergebnis."],
  },
  seo: {
    title: "{company} ({ticker}): Finanzkennzahlen und Bewertung",
    description: "Analysiere Bewertung, Profitabilität, Liquidität, Verschuldung, Dividenden und Effizienz von {company} ({ticker}) über mehrere Zeiträume.",
    keywords: "{ticker} Finanzkennzahlen, {company} Bewertung, KGV, Eigenkapitalrendite, Verschuldungsgrad, Profitabilität, Liquidität, Dividendenrendite",
    name: "Finanzkennzahlenanalyse für {company} ({ticker})",
    headline: "Bewertung und Finanzkennzahlen von {company}",
    structuredDescription: "Finanzkennzahlenanalyse für {company} ({ticker}) zu Bewertung, Profitabilität, Liquidität, Verschuldung und Effizienz.",
    aboutName: "Finanzkennzahlenanalyse",
    aboutDescription: "Analyse von Bewertung, Profitabilität, Liquidität, Verschuldung und operativer Effizienz.",
    home: "Startseite",
    stocks: "Aktien",
    financialStatements: "Finanzberichte",
    financialRatios: "Finanzkennzahlen",
  },
} satisfies FinancialRatiosSourceCatalog;
