import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "Ratios and Metrics",
  metrics: {
    priceToEarningsRatio: ["P/E Ratio", "Compares the share price with earnings per share to show how highly the market values current profits."],
    priceToEarningsGrowthRatio: ["PEG Ratio", "Compares the P/E ratio with expected earnings growth; a lower value can suggest a cheaper growth valuation."],
    returnOnEquity: ["Return on Equity", "Shows how efficiently a company turns shareholders’ equity into profit."],
    returnOnInvestedCapital: ["Return on Invested Capital", "Shows how effectively a company earns a return on the capital invested in the business."],
    netProfitMargin: ["Net Profit Margin", "The percentage of revenue left as net profit after all costs, interest, and taxes."],
    freeCashFlowYield: ["FCF Yield", "Compares free cash flow with market value to show the cash return available to investors."],
    debtToEquityRatio: ["Debt / Equity Ratio", "Compares total debt with shareholders’ equity; a higher ratio usually means greater financial leverage."],
    currentRatio: ["Current Ratio", "Compares current assets with current liabilities to gauge short-term liquidity."],
    forwardPE: ["Forward P/E Ratio", "Compares the share price with forecast earnings for the next fiscal year."],
    priceToSalesRatio: ["P/S Ratio", "Compares the company’s market value with its revenue."],
    priceToBookRatio: ["P/B Ratio", "Compares the share price with book value per share."],
    priceToFreeCashFlowRatio: ["P/FCF Ratio", "Compares market value with free cash flow rather than accounting earnings."],
    priceToOperatingCashFlowRatio: ["P/OCF Ratio", "Compares market value with cash generated from operations."],
    enterpriseValueMultiple: ["EV/EBITDA", "Compares enterprise value with EBITDA to assess valuation before financing and non-cash charges."],
    priceToFairValue: ["Price to Fair Value", "Compares the current share price with an estimated fundamental fair value."],
    returnOnAssets: ["Return on Assets", "Shows how efficiently a company uses its assets to generate profit."],
    returnOnCapitalEmployed: ["Return on Capital Employed", "Shows how efficiently operating profit is generated from equity and debt capital."],
    grossProfitMargin: ["Gross Profit Margin", "The percentage of revenue left after direct production costs."],
    operatingProfitMargin: ["Operating Profit Margin", "The percentage of revenue left as operating profit after operating expenses."],
    ebitdaMargin: ["EBITDA Margin", "EBITDA as a percentage of revenue, before interest, taxes, depreciation, and amortization."],
    ebitMargin: ["EBIT Margin", "Earnings before interest and taxes as a percentage of revenue."],
    pretaxProfitMargin: ["Pretax Profit Margin", "Profit before tax as a percentage of revenue."],
    freeCashFlowMargin: ["FCF Margin", "Free cash flow as a percentage of revenue after capital spending."],
    bottomLineProfitMargin: ["Bottom Line Profit Margin", "Final net profit as a percentage of revenue after all expenses and taxes."],
    continuousOperationsProfitMargin: ["Continuing Operations Margin", "Profitability from ongoing activities, excluding discontinued operations."],
    freeCashFlowPerShare: ["Free Cash Flow Per Share", "Free cash flow divided by the number of shares outstanding."],
    revenuePerShare: ["Revenue Per Share", "Revenue divided by the number of shares outstanding."],
    netIncomePerShare: ["Net Income Per Share", "Net profit attributable to each outstanding common share."],
    operatingCashFlowPerShare: ["Operating Cash Flow Per Share", "Cash generated from operations divided by shares outstanding."],
    bookValuePerShare: ["Book Value Per Share", "Shareholders’ equity divided by shares outstanding."],
    tangibleBookValuePerShare: ["Tangible Book Value Per Share", "Book value per share after excluding goodwill and other intangible assets."],
    cashPerShare: ["Cash Per Share", "Cash and cash equivalents divided by shares outstanding."],
    shareholdersEquityPerShare: ["Shareholders’ Equity Per Share", "Equity attributable to shareholders divided by shares outstanding."],
    interestDebtPerShare: ["Interest-Bearing Debt Per Share", "Interest-bearing debt divided by shares outstanding."],
    capexPerShare: ["CapEx Per Share", "Capital expenditure divided by shares outstanding."],
    dividendYield: ["Dividend Yield", "Annual dividends per share as a proportion of the share price."],
    dividendPerShare: ["Dividend Per Share", "Total dividends paid divided by shares outstanding."],
    dividendPayoutRatio: ["Payout Ratio", "The percentage of profit paid to shareholders as dividends."],
    dividendYieldPercentage: ["Dividend Yield %", "Annual dividends relative to the share price, expressed as a percentage."],
    quickRatio: ["Quick Ratio", "Compares liquid current assets with current liabilities, excluding inventory."],
    cashRatio: ["Cash Ratio", "Compares cash and cash equivalents with current liabilities."],
    debtToAssetsRatio: ["Debt to Assets Ratio", "The share of assets financed with debt."],
    debtToCapitalRatio: ["Debt to Capital Ratio", "Compares debt with total capital, meaning debt plus equity."],
    longTermDebtToCapitalRatio: ["Long-Term Debt to Capital", "The share of total capital financed with long-term debt."],
    debtToMarketCap: ["Debt to Market Cap", "Compares total debt with the company’s stock-market value."],
    financialLeverageRatio: ["Financial Leverage Ratio", "Shows how heavily a company relies on debt to finance its assets."],
    solvencyRatio: ["Solvency Ratio", "Indicates the company’s ability to meet long-term financial obligations."],
    interestCoverageRatio: ["Interest Coverage", "Shows how many times operating profit can cover interest expense."],
    operatingCashFlowRatio: ["OCF Ratio", "Shows how well operating cash flow covers current liabilities."],
    operatingCashFlowSalesRatio: ["OCF / Sales Ratio", "Shows how effectively revenue is converted into operating cash flow."],
    freeCashFlowOperatingCashFlowRatio: ["FCF / OCF Ratio", "The share of operating cash flow left as free cash flow after capital spending."],
    debtServiceCoverageRatio: ["Debt Service Coverage", "Shows how well operating income covers debt payments."],
    operatingCashFlowCoverageRatio: ["OCF Coverage Ratio", "Shows how well operating cash flow covers total debt obligations."],
    capitalExpenditureCoverageRatio: ["CapEx Coverage Ratio", "Shows how well operating cash flow covers capital expenditure."],
    dividendPaidAndCapexCoverageRatio: ["Dividend & CapEx Coverage", "Shows how well operating cash flow covers both dividends and capital spending."],
    shortTermOperatingCashFlowCoverageRatio: ["Short-Term OCF Coverage", "Shows how well operating cash flow covers short-term obligations."],
    assetTurnover: ["Asset Turnover", "Shows how efficiently assets are used to generate revenue."],
    inventoryTurnover: ["Inventory Turnover", "Shows how often inventory is sold and replaced during a period."],
    receivablesTurnover: ["Receivables Turnover", "Shows how efficiently the company collects credit sales."],
    payablesTurnover: ["Payables Turnover", "Shows how quickly the company pays suppliers."],
    fixedAssetTurnover: ["Fixed Asset Turnover", "Shows how efficiently fixed assets are used to generate revenue."],
    workingCapitalTurnoverRatio: ["Working Capital Turnover", "Shows how efficiently working capital is used to generate revenue."],
    effectiveTaxRate: ["Effective Tax Rate", "The average tax rate paid on pretax profit."],
    netIncomePerEBT: ["Net Income / EBT", "The share of pretax earnings left as net income after tax."],
    ebtPerEbit: ["EBT / EBIT", "Shows the effect of interest and non-operating items on operating earnings."],
  },
  seo: {
    title: "{company} ({ticker}) Financial Ratios & Valuation Metrics",
    description: "Explore {company} ({ticker}) valuation, profitability, liquidity, leverage, dividend, and efficiency ratios across multiple periods.",
    keywords: "{ticker} financial ratios, {company} valuation, P/E ratio, return on equity, debt to equity, profitability, liquidity, dividend yield",
    name: "{company} ({ticker}) Financial Ratio Analysis",
    headline: "{company} Valuation and Financial Metrics",
    structuredDescription: "Financial ratio analysis for {company} ({ticker}), covering valuation, profitability, liquidity, leverage, and efficiency.",
    aboutName: "Financial Ratio Analysis",
    aboutDescription: "Analysis of valuation, profitability, liquidity, leverage, and operating efficiency.",
    home: "Home",
    stocks: "Stocks",
    financialStatements: "Financial Statements",
    financialRatios: "Financial Ratios",
  },
} satisfies FinancialRatiosSourceCatalog;
