import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "Ratios y métricas",
  metrics: {
    priceToEarningsRatio: ["Ratio PER", "Compara el precio de la acción con el beneficio por acción y muestra cuánto valora el mercado los beneficios actuales."],
    priceToEarningsGrowthRatio: ["Ratio PEG", "Compara el PER con el crecimiento esperado del beneficio; un valor menor puede indicar una valoración de crecimiento más atractiva."],
    returnOnEquity: ["Rentabilidad sobre recursos propios", "Muestra la eficiencia con la que la empresa convierte el patrimonio de los accionistas en beneficios."],
    returnOnInvestedCapital: ["Rentabilidad sobre el capital invertido", "Muestra la rentabilidad que obtiene la empresa del capital invertido en el negocio."],
    netProfitMargin: ["Margen neto", "Porcentaje de ingresos que queda como beneficio neto después de todos los costes, intereses e impuestos."],
    freeCashFlowYield: ["Rentabilidad del flujo de caja libre", "Compara el flujo de caja libre con el valor de mercado y muestra el retorno en efectivo disponible para el inversor."],
    debtToEquityRatio: ["Deuda / patrimonio", "Compara la deuda total con el patrimonio; un valor mayor suele implicar más apalancamiento financiero."],
    currentRatio: ["Ratio de liquidez", "Compara los activos corrientes con los pasivos corrientes para medir la liquidez a corto plazo."],
    forwardPE: ["PER estimado", "Compara el precio de la acción con el beneficio previsto para el próximo ejercicio."],
    priceToSalesRatio: ["Ratio precio / ventas", "Compara el valor de mercado de la empresa con sus ingresos."],
    priceToBookRatio: ["Ratio precio / valor contable", "Compara el precio de la acción con el valor contable por acción."],
    priceToFreeCashFlowRatio: ["Precio / flujo de caja libre", "Compara el valor de mercado con el flujo de caja libre en lugar del beneficio contable."],
    priceToOperatingCashFlowRatio: ["Precio / flujo de caja operativo", "Compara el valor de mercado con el efectivo generado por la actividad."],
    enterpriseValueMultiple: ["VE/EBITDA", "Compara el valor de empresa con el EBITDA para valorar el negocio antes de financiación y cargos no monetarios."],
    priceToFairValue: ["Precio / valor razonable", "Compara el precio actual de la acción con una estimación de su valor razonable fundamental."],
    returnOnAssets: ["Rentabilidad sobre activos", "Muestra la eficiencia con la que la empresa usa sus activos para generar beneficios."],
    returnOnCapitalEmployed: ["Rentabilidad sobre el capital empleado", "Muestra la eficiencia con la que el capital propio y la deuda generan beneficio operativo."],
    grossProfitMargin: ["Margen bruto", "Porcentaje de ingresos que queda después de los costes directos de producción."],
    operatingProfitMargin: ["Margen operativo", "Porcentaje de ingresos que queda como beneficio operativo tras los gastos de explotación."],
    ebitdaMargin: ["Margen EBITDA", "EBITDA como porcentaje de los ingresos, antes de intereses, impuestos, depreciaciones y amortizaciones."],
    ebitMargin: ["Margen EBIT", "Beneficio antes de intereses e impuestos como porcentaje de los ingresos."],
    pretaxProfitMargin: ["Margen antes de impuestos", "Beneficio antes de impuestos como porcentaje de los ingresos."],
    freeCashFlowMargin: ["Margen de flujo de caja libre", "Flujo de caja libre como porcentaje de los ingresos después de inversiones."],
    bottomLineProfitMargin: ["Margen neto final", "Beneficio neto final como porcentaje de los ingresos después de todos los gastos e impuestos."],
    continuousOperationsProfitMargin: ["Margen de operaciones continuadas", "Rentabilidad de las actividades que continúan, sin incluir operaciones interrumpidas."],
    freeCashFlowPerShare: ["Flujo de caja libre por acción", "Flujo de caja libre dividido entre las acciones en circulación."],
    revenuePerShare: ["Ingresos por acción", "Ingresos divididos entre las acciones en circulación."],
    netIncomePerShare: ["Beneficio neto por acción", "Beneficio neto atribuible a cada acción ordinaria en circulación."],
    operatingCashFlowPerShare: ["Flujo de caja operativo por acción", "Efectivo generado por la actividad dividido entre las acciones en circulación."],
    bookValuePerShare: ["Valor contable por acción", "Patrimonio de los accionistas dividido entre las acciones en circulación."],
    tangibleBookValuePerShare: ["Valor contable tangible por acción", "Valor contable por acción sin fondo de comercio ni otros activos intangibles."],
    cashPerShare: ["Efectivo por acción", "Efectivo y equivalentes dividido entre las acciones en circulación."],
    shareholdersEquityPerShare: ["Patrimonio por acción", "Patrimonio atribuible a los accionistas dividido entre las acciones en circulación."],
    interestDebtPerShare: ["Deuda con intereses por acción", "Deuda que genera intereses dividida entre las acciones en circulación."],
    capexPerShare: ["CapEx por acción", "Inversión en activos fijos dividida entre las acciones en circulación."],
    dividendYield: ["Rentabilidad por dividendo", "Dividendo anual por acción en relación con el precio de la acción."],
    dividendPerShare: ["Dividendo por acción", "Dividendos pagados divididos entre las acciones en circulación."],
    dividendPayoutRatio: ["Ratio de reparto", "Porcentaje del beneficio que se distribuye a los accionistas como dividendo."],
    dividendYieldPercentage: ["Rentabilidad por dividendo %", "Dividendo anual respecto al precio de la acción, expresado como porcentaje."],
    quickRatio: ["Prueba ácida", "Compara los activos corrientes más líquidos, sin existencias, con los pasivos corrientes."],
    cashRatio: ["Ratio de efectivo", "Compara el efectivo y sus equivalentes con los pasivos corrientes."],
    debtToAssetsRatio: ["Deuda / activos", "Parte de los activos financiada con deuda."],
    debtToCapitalRatio: ["Deuda / capital", "Compara la deuda con el capital total, es decir, deuda más patrimonio."],
    longTermDebtToCapitalRatio: ["Deuda a largo plazo / capital", "Parte del capital total financiada con deuda a largo plazo."],
    debtToMarketCap: ["Deuda / capitalización bursátil", "Compara la deuda total con el valor bursátil de la empresa."],
    financialLeverageRatio: ["Apalancamiento financiero", "Muestra cuánto depende la empresa de la deuda para financiar sus activos."],
    solvencyRatio: ["Ratio de solvencia", "Indica la capacidad de la empresa para cumplir sus obligaciones financieras a largo plazo."],
    interestCoverageRatio: ["Cobertura de intereses", "Muestra cuántas veces el beneficio operativo puede cubrir los gastos por intereses."],
    operatingCashFlowRatio: ["Ratio de flujo de caja operativo", "Muestra cuánto cubre el flujo de caja operativo los pasivos corrientes."],
    operatingCashFlowSalesRatio: ["Flujo de caja operativo / ventas", "Muestra la eficiencia con la que las ventas se convierten en flujo de caja operativo."],
    freeCashFlowOperatingCashFlowRatio: ["Flujo de caja libre / operativo", "Parte del flujo de caja operativo que queda libre después de las inversiones."],
    debtServiceCoverageRatio: ["Cobertura del servicio de la deuda", "Muestra cuánto cubre el resultado operativo los pagos de la deuda."],
    operatingCashFlowCoverageRatio: ["Cobertura por flujo de caja operativo", "Muestra cuánto cubre el flujo de caja operativo las obligaciones totales de deuda."],
    capitalExpenditureCoverageRatio: ["Cobertura de CapEx", "Muestra cuánto cubre el flujo de caja operativo las inversiones en activos fijos."],
    dividendPaidAndCapexCoverageRatio: ["Cobertura de dividendos y CapEx", "Muestra cuánto cubre el flujo de caja operativo los dividendos y las inversiones."],
    shortTermOperatingCashFlowCoverageRatio: ["Cobertura de efectivo a corto plazo", "Muestra cuánto cubre el flujo de caja operativo las obligaciones a corto plazo."],
    assetTurnover: ["Rotación de activos", "Muestra la eficiencia con la que los activos generan ingresos."],
    inventoryTurnover: ["Rotación de existencias", "Muestra cuántas veces se venden y reponen las existencias durante un periodo."],
    receivablesTurnover: ["Rotación de cuentas por cobrar", "Muestra la eficiencia con la que la empresa cobra sus ventas a crédito."],
    payablesTurnover: ["Rotación de cuentas por pagar", "Muestra la rapidez con la que la empresa paga a sus proveedores."],
    fixedAssetTurnover: ["Rotación de activos fijos", "Muestra la eficiencia con la que los activos fijos generan ingresos."],
    workingCapitalTurnoverRatio: ["Rotación del capital circulante", "Muestra la eficiencia con la que el capital circulante genera ingresos."],
    effectiveTaxRate: ["Tipo impositivo efectivo", "Tipo medio de impuestos pagado sobre el beneficio antes de impuestos."],
    netIncomePerEBT: ["Beneficio neto / BAI", "Parte del beneficio antes de impuestos que queda como beneficio neto."],
    ebtPerEbit: ["BAI / EBIT", "Muestra el efecto de los intereses y partidas no operativas sobre el beneficio operativo."],
  },
  seo: {
    title: "Ratios financieros y valoración de {company} ({ticker})",
    description: "Consulta la valoración, rentabilidad, liquidez, deuda, dividendos y eficiencia de {company} ({ticker}) durante varios periodos.",
    keywords: "ratios financieros {ticker}, valoración {company}, ratio PER, rentabilidad sobre recursos propios, deuda sobre patrimonio, rentabilidad, liquidez, dividendo",
    name: "Análisis de ratios financieros de {company} ({ticker})",
    headline: "Valoración y métricas financieras de {company}",
    structuredDescription: "Análisis de ratios de {company} ({ticker}) sobre valoración, rentabilidad, liquidez, deuda y eficiencia.",
    aboutName: "Análisis de ratios financieros",
    aboutDescription: "Análisis de valoración, rentabilidad, liquidez, deuda y eficiencia operativa.",
    home: "Inicio",
    stocks: "Acciones",
    financialStatements: "Estados financieros",
    financialRatios: "Ratios financieros",
  },
} satisfies FinancialRatiosSourceCatalog;
