import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "Ratios et indicateurs",
  metrics: {
    priceToEarningsRatio: ["Ratio cours / bénéfice", "Compare le cours de l’action au bénéfice par action et indique la valorisation accordée aux bénéfices actuels."],
    priceToEarningsGrowthRatio: ["Ratio PEG", "Rapporte le ratio cours / bénéfice à la croissance attendue des bénéfices ; une valeur plus basse peut indiquer une valorisation de croissance plus attractive."],
    returnOnEquity: ["Rentabilité des capitaux propres", "Mesure l’efficacité avec laquelle l’entreprise transforme les capitaux propres en bénéfices."],
    returnOnInvestedCapital: ["Rentabilité du capital investi", "Mesure le rendement obtenu sur le capital investi dans l’activité."],
    netProfitMargin: ["Marge nette", "Part du chiffre d’affaires conservée en bénéfice net après toutes les charges, les intérêts et les impôts."],
    freeCashFlowYield: ["Rendement du flux de trésorerie disponible", "Compare le flux de trésorerie disponible à la valeur de marché et montre le rendement en trésorerie offert aux investisseurs."],
    debtToEquityRatio: ["Dette / capitaux propres", "Compare la dette totale aux capitaux propres ; une valeur élevée traduit généralement un levier financier plus important."],
    currentRatio: ["Ratio de liquidité générale", "Compare les actifs courants aux passifs courants pour évaluer la liquidité à court terme."],
    forwardPE: ["Ratio cours / bénéfice prévisionnel", "Compare le cours de l’action au bénéfice prévu pour le prochain exercice."],
    priceToSalesRatio: ["Ratio cours / chiffre d’affaires", "Compare la valeur de marché de l’entreprise à son chiffre d’affaires."],
    priceToBookRatio: ["Ratio cours / valeur comptable", "Compare le cours de l’action à la valeur comptable par action."],
    priceToFreeCashFlowRatio: ["Cours / flux de trésorerie disponible", "Compare la valeur de marché au flux de trésorerie disponible plutôt qu’au bénéfice comptable."],
    priceToOperatingCashFlowRatio: ["Cours / flux de trésorerie d’exploitation", "Compare la valeur de marché à la trésorerie générée par l’exploitation."],
    enterpriseValueMultiple: ["VE/EBITDA", "Compare la valeur d’entreprise à l’EBITDA pour évaluer l’activité avant financement et charges non décaissées."],
    priceToFairValue: ["Cours / juste valeur", "Compare le cours actuel à une estimation fondamentale de la juste valeur."],
    returnOnAssets: ["Rentabilité des actifs", "Mesure l’efficacité avec laquelle l’entreprise utilise ses actifs pour générer des bénéfices."],
    returnOnCapitalEmployed: ["Rentabilité des capitaux employés", "Mesure l’efficacité avec laquelle capitaux propres et dette génèrent un résultat opérationnel."],
    grossProfitMargin: ["Marge brute", "Part du chiffre d’affaires restante après les coûts directs de production."],
    operatingProfitMargin: ["Marge opérationnelle", "Part du chiffre d’affaires restante en résultat opérationnel après les charges d’exploitation."],
    ebitdaMargin: ["Marge d’EBITDA", "EBITDA en pourcentage du chiffre d’affaires, avant intérêts, impôts et amortissements."],
    ebitMargin: ["Marge d’EBIT", "Résultat avant intérêts et impôts en pourcentage du chiffre d’affaires."],
    pretaxProfitMargin: ["Marge avant impôts", "Résultat avant impôts en pourcentage du chiffre d’affaires."],
    freeCashFlowMargin: ["Marge de flux de trésorerie disponible", "Flux de trésorerie disponible en pourcentage du chiffre d’affaires après investissements."],
    bottomLineProfitMargin: ["Marge nette finale", "Bénéfice net final en pourcentage du chiffre d’affaires après toutes les charges et les impôts."],
    continuousOperationsProfitMargin: ["Marge des activités poursuivies", "Rentabilité des activités maintenues, hors activités abandonnées."],
    freeCashFlowPerShare: ["Flux de trésorerie disponible par action", "Flux de trésorerie disponible divisé par le nombre d’actions en circulation."],
    revenuePerShare: ["Chiffre d’affaires par action", "Chiffre d’affaires divisé par le nombre d’actions en circulation."],
    netIncomePerShare: ["Bénéfice net par action", "Bénéfice net attribuable à chaque action ordinaire en circulation."],
    operatingCashFlowPerShare: ["Flux de trésorerie d’exploitation par action", "Trésorerie générée par l’exploitation divisée par le nombre d’actions en circulation."],
    bookValuePerShare: ["Valeur comptable par action", "Capitaux propres divisés par le nombre d’actions en circulation."],
    tangibleBookValuePerShare: ["Valeur comptable tangible par action", "Valeur comptable par action hors goodwill et autres actifs incorporels."],
    cashPerShare: ["Trésorerie par action", "Trésorerie et équivalents divisés par le nombre d’actions en circulation."],
    shareholdersEquityPerShare: ["Capitaux propres par action", "Capitaux propres attribuables aux actionnaires divisés par les actions en circulation."],
    interestDebtPerShare: ["Dette portant intérêt par action", "Dette portant intérêt divisée par le nombre d’actions en circulation."],
    capexPerShare: ["Investissements par action", "Dépenses d’investissement divisées par le nombre d’actions en circulation."],
    dividendYield: ["Rendement du dividende", "Dividende annuel par action rapporté au cours de l’action."],
    dividendPerShare: ["Dividende par action", "Total des dividendes versés divisé par le nombre d’actions en circulation."],
    dividendPayoutRatio: ["Taux de distribution", "Part du bénéfice distribuée aux actionnaires sous forme de dividendes."],
    dividendYieldPercentage: ["Rendement du dividende %", "Dividende annuel rapporté au cours de l’action, exprimé en pourcentage."],
    quickRatio: ["Ratio de liquidité réduite", "Compare les actifs courants les plus liquides, hors stocks, aux passifs courants."],
    cashRatio: ["Ratio de liquidité immédiate", "Compare la trésorerie et ses équivalents aux passifs courants."],
    debtToAssetsRatio: ["Dette / actifs", "Part des actifs financée par la dette."],
    debtToCapitalRatio: ["Dette / capital", "Compare la dette au capital total, soit la dette plus les capitaux propres."],
    longTermDebtToCapitalRatio: ["Dette à long terme / capital", "Part du capital total financée par la dette à long terme."],
    debtToMarketCap: ["Dette / capitalisation boursière", "Compare la dette totale à la valeur boursière de l’entreprise."],
    financialLeverageRatio: ["Levier financier", "Indique dans quelle mesure l’entreprise s’appuie sur la dette pour financer ses actifs."],
    solvencyRatio: ["Ratio de solvabilité", "Indique la capacité de l’entreprise à honorer ses engagements financiers à long terme."],
    interestCoverageRatio: ["Couverture des intérêts", "Indique combien de fois le résultat opérationnel couvre les charges d’intérêts."],
    operatingCashFlowRatio: ["Ratio de flux de trésorerie d’exploitation", "Indique dans quelle mesure le flux de trésorerie d’exploitation couvre les passifs courants."],
    operatingCashFlowSalesRatio: ["Flux de trésorerie d’exploitation / ventes", "Mesure l’efficacité de conversion du chiffre d’affaires en trésorerie d’exploitation."],
    freeCashFlowOperatingCashFlowRatio: ["Flux de trésorerie disponible / exploitation", "Part du flux de trésorerie d’exploitation restante après les investissements."],
    debtServiceCoverageRatio: ["Couverture du service de la dette", "Indique dans quelle mesure le résultat opérationnel couvre les remboursements de dette."],
    operatingCashFlowCoverageRatio: ["Couverture par la trésorerie d’exploitation", "Indique dans quelle mesure la trésorerie d’exploitation couvre l’ensemble des obligations de dette."],
    capitalExpenditureCoverageRatio: ["Couverture des investissements", "Indique dans quelle mesure la trésorerie d’exploitation couvre les dépenses d’investissement."],
    dividendPaidAndCapexCoverageRatio: ["Couverture des dividendes et investissements", "Indique dans quelle mesure la trésorerie d’exploitation couvre à la fois les dividendes et les investissements."],
    shortTermOperatingCashFlowCoverageRatio: ["Couverture de trésorerie à court terme", "Indique dans quelle mesure la trésorerie d’exploitation couvre les obligations à court terme."],
    assetTurnover: ["Rotation des actifs", "Mesure l’efficacité avec laquelle les actifs génèrent du chiffre d’affaires."],
    inventoryTurnover: ["Rotation des stocks", "Indique combien de fois les stocks sont vendus et renouvelés sur une période."],
    receivablesTurnover: ["Rotation des créances clients", "Mesure l’efficacité avec laquelle l’entreprise recouvre ses ventes à crédit."],
    payablesTurnover: ["Rotation des dettes fournisseurs", "Indique la rapidité avec laquelle l’entreprise paie ses fournisseurs."],
    fixedAssetTurnover: ["Rotation des immobilisations", "Mesure l’efficacité avec laquelle les immobilisations génèrent du chiffre d’affaires."],
    workingCapitalTurnoverRatio: ["Rotation du fonds de roulement", "Mesure l’efficacité avec laquelle le fonds de roulement génère du chiffre d’affaires."],
    effectiveTaxRate: ["Taux d’imposition effectif", "Taux moyen d’impôt payé sur le résultat avant impôts."],
    netIncomePerEBT: ["Résultat net / résultat avant impôts", "Part du résultat avant impôts restante en résultat net après impôts."],
    ebtPerEbit: ["Résultat avant impôts / EBIT", "Montre l’effet des intérêts et des éléments non opérationnels sur le résultat opérationnel."],
  },
  seo: {
    title: "Ratios financiers et valorisation de {company} ({ticker})",
    description: "Analysez la valorisation, la rentabilité, la liquidité, l’endettement, les dividendes et l’efficacité de {company} ({ticker}) sur plusieurs périodes.",
    keywords: "ratios financiers {ticker}, valorisation {company}, ratio cours bénéfice, rentabilité des capitaux propres, dette sur capitaux propres, rentabilité, liquidité, dividende",
    name: "Analyse des ratios financiers de {company} ({ticker})",
    headline: "Valorisation et indicateurs financiers de {company}",
    structuredDescription: "Analyse des ratios de {company} ({ticker}) couvrant valorisation, rentabilité, liquidité, endettement et efficacité.",
    aboutName: "Analyse des ratios financiers",
    aboutDescription: "Analyse de la valorisation, de la rentabilité, de la liquidité, de l’endettement et de l’efficacité opérationnelle.",
    home: "Accueil",
    stocks: "Actions",
    financialStatements: "États financiers",
    financialRatios: "Ratios financiers",
  },
} satisfies FinancialRatiosSourceCatalog;
