import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "財務指標",
  metrics: {
    priceToEarningsRatio: ["PER", "株価を1株当たり純利益と比べ、現在の利益が市場でどれだけ高く評価されているかを示します。"],
    priceToEarningsGrowthRatio: ["PEGレシオ", "PERを予想利益成長率と比べた指標です。数値が低いほど成長に対して割安と見ることができます。"],
    returnOnEquity: ["ROE", "自己資本をどれだけ効率よく利益に変えているかを示します。"],
    returnOnInvestedCapital: ["ROIC", "事業に投じた資本からどれだけ効率よく利益を上げているかを示します。"],
    netProfitMargin: ["純利益率", "すべての費用、利息、税金を差し引いたあとに純利益として残る売上高の割合です。"],
    freeCashFlowYield: ["FCF利回り", "フリーキャッシュフローを時価総額と比べ、投資家が受け取れるキャッシュの利回りを示します。"],
    debtToEquityRatio: ["D/Eレシオ", "有利子負債を自己資本と比べた指標です。数値が高いほど財務レバレッジが大きくなります。"],
    currentRatio: ["流動比率", "流動資産を流動負債と比べ、短期の支払能力を測ります。"],
    forwardPE: ["予想PER", "株価を翌事業年度の予想利益と比べた指標です。"],
    priceToSalesRatio: ["PSR", "時価総額を売上高と比べた指標です。"],
    priceToBookRatio: ["PBR", "株価を1株当たり純資産と比べた指標です。"],
    priceToFreeCashFlowRatio: ["株価FCF倍率", "会計上の利益ではなく、フリーキャッシュフローと時価総額を比べた指標です。"],
    priceToOperatingCashFlowRatio: ["株価営業CF倍率", "時価総額を営業活動で生み出したキャッシュと比べた指標です。"],
    enterpriseValueMultiple: ["EV/EBITDA", "企業価値をEBITDAと比べ、資金調達や非現金費用の影響を除いて割安さを判断します。"],
    priceToFairValue: ["株価/適正価値", "現在の株価をファンダメンタルズから推定した適正価値と比べた指標です。"],
    returnOnAssets: ["ROA", "保有する資産をどれだけ効率よく利益につなげているかを示します。"],
    returnOnCapitalEmployed: ["ROCE", "自己資本と負債を合わせた資本から、どれだけ効率よく営業利益を生んでいるかを示します。"],
    grossProfitMargin: ["売上総利益率", "直接の製造原価を差し引いたあとに残る売上高の割合です。"],
    operatingProfitMargin: ["営業利益率", "販売費や一般管理費を差し引いたあとに営業利益として残る売上高の割合です。"],
    ebitdaMargin: ["EBITDAマージン", "利息、税金、減価償却費を差し引く前のEBITDAが売上高に占める割合です。"],
    ebitMargin: ["EBITマージン", "利息と税金を差し引く前の利益が売上高に占める割合です。"],
    pretaxProfitMargin: ["税引前利益率", "税引前利益が売上高に占める割合です。"],
    freeCashFlowMargin: ["FCFマージン", "設備投資を差し引いたあとのフリーキャッシュフローが売上高に占める割合です。"],
    bottomLineProfitMargin: ["最終利益率", "すべての費用と税金を差し引いた最終的な純利益が売上高に占める割合です。"],
    continuousOperationsProfitMargin: ["継続事業利益率", "非継続事業を除いた、現在も続けている事業の収益性です。"],
    freeCashFlowPerShare: ["1株当たりFCF", "フリーキャッシュフローを発行済株式数で割った値です。"],
    revenuePerShare: ["1株当たり売上高", "売上高を発行済株式数で割った値です。"],
    netIncomePerShare: ["1株当たり純利益", "発行済普通株式1株に帰属する純利益です。"],
    operatingCashFlowPerShare: ["1株当たり営業CF", "営業活動で得たキャッシュを発行済株式数で割った値です。"],
    bookValuePerShare: ["1株当たり純資産", "自己資本を発行済株式数で割った値です。"],
    tangibleBookValuePerShare: ["1株当たり有形純資産", "のれんやその他の無形資産を除いた1株当たり純資産です。"],
    cashPerShare: ["1株当たり現金", "現金及び現金同等物を発行済株式数で割った値です。"],
    shareholdersEquityPerShare: ["1株当たり自己資本", "株主に帰属する自己資本を発行済株式数で割った値です。"],
    interestDebtPerShare: ["1株当たり有利子負債", "有利子負債を発行済株式数で割った値です。"],
    capexPerShare: ["1株当たり設備投資", "設備投資額を発行済株式数で割った値です。"],
    dividendYield: ["配当利回り", "1株当たりの年間配当金が株価に占める割合です。"],
    dividendPerShare: ["1株当たり配当金", "支払配当金の総額を発行済株式数で割った値です。"],
    dividendPayoutRatio: ["配当性向", "利益のうち株主に配当として支払われた割合です。"],
    dividendYieldPercentage: ["配当利回り（%）", "年間配当金の株価に対する割合を百分率で表した値です。"],
    quickRatio: ["当座比率", "棚卸資産を除いた流動資産を流動負債と比べた指標です。"],
    cashRatio: ["現金比率", "現金及び現金同等物を流動負債と比べた指標です。"],
    debtToAssetsRatio: ["総資産負債比率", "総資産のうち負債で賄われている割合です。"],
    debtToCapitalRatio: ["負債/総資本", "負債を、負債と自己資本を合わせた総資本と比べた指標です。"],
    longTermDebtToCapitalRatio: ["長期負債/総資本", "総資本のうち長期負債で賄われている割合です。"],
    debtToMarketCap: ["負債/時価総額", "有利子負債の総額を時価総額と比べた指標です。"],
    financialLeverageRatio: ["財務レバレッジ", "資産の調達を負債にどれだけ頼っているかを示します。"],
    solvencyRatio: ["支払能力比率", "長期の債務を返済していく力を示します。"],
    interestCoverageRatio: ["インタレストカバレッジ", "営業利益で支払利息を何倍まかなえるかを示します。"],
    operatingCashFlowRatio: ["営業CF比率", "営業キャッシュフローで流動負債をどれだけまかなえるかを示します。"],
    operatingCashFlowSalesRatio: ["営業CF/売上高", "売上高をどれだけ営業キャッシュフローに変えられているかを示します。"],
    freeCashFlowOperatingCashFlowRatio: ["FCF/営業CF", "営業キャッシュフローのうち、設備投資後にフリーキャッシュフローとして残る割合です。"],
    debtServiceCoverageRatio: ["債務返済カバレッジ", "営業利益で元利返済をどれだけまかなえるかを示します。"],
    operatingCashFlowCoverageRatio: ["営業CFカバレッジ", "営業キャッシュフローで有利子負債の総額をどれだけまかなえるかを示します。"],
    capitalExpenditureCoverageRatio: ["設備投資カバレッジ", "営業キャッシュフローで設備投資をどれだけまかなえるかを示します。"],
    dividendPaidAndCapexCoverageRatio: ["配当・設備投資カバレッジ", "営業キャッシュフローで配当と設備投資の両方をどれだけまかなえるかを示します。"],
    shortTermOperatingCashFlowCoverageRatio: ["短期債務カバレッジ", "営業キャッシュフローで短期の債務をどれだけまかなえるかを示します。"],
    assetTurnover: ["総資産回転率", "資産をどれだけ効率よく売上高につなげているかを示します。"],
    inventoryTurnover: ["棚卸資産回転率", "一定期間に在庫が何回入れ替わったかを示します。"],
    receivablesTurnover: ["売上債権回転率", "掛け売りの代金をどれだけ効率よく回収できているかを示します。"],
    payablesTurnover: ["仕入債務回転率", "仕入先への支払いがどれだけ早いかを示します。"],
    fixedAssetTurnover: ["固定資産回転率", "固定資産をどれだけ効率よく売上高につなげているかを示します。"],
    workingCapitalTurnoverRatio: ["運転資本回転率", "運転資本をどれだけ効率よく売上高につなげているかを示します。"],
    effectiveTaxRate: ["実効税率", "税引前利益に対して実際に負担した税率の平均です。"],
    netIncomePerEBT: ["純利益/税引前利益", "税引前利益のうち、納税後に純利益として残る割合です。"],
    ebtPerEbit: ["税引前利益/EBIT", "利息や営業外損益が営業利益にどれだけ影響しているかを示します。"],
  },
  seo: {
    title: "{company}（{ticker}）の財務指標・バリュエーション指標",
    description: "{company}（{ticker}）のバリュエーション、収益性、流動性、レバレッジ、配当、効率性の各指標を複数期間で確認できます。",
    keywords: "{ticker} 財務指標, {company} バリュエーション, PER, ROE, D/Eレシオ, 収益性, 流動性, 配当利回り",
    name: "{company}（{ticker}）の財務指標分析",
    headline: "{company}のバリュエーションと財務指標",
    structuredDescription: "{company}（{ticker}）の財務指標分析です。バリュエーション、収益性、流動性、レバレッジ、効率性を扱います。",
    aboutName: "財務指標分析",
    aboutDescription: "バリュエーション、収益性、流動性、レバレッジ、事業効率の分析です。",
    home: "ホーム",
    stocks: "株式",
    financialStatements: "財務諸表",
    financialRatios: "財務指標",
  },
} satisfies FinancialRatiosSourceCatalog;
