import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "재무비율 및 지표",
  metrics: {
    priceToEarningsRatio: ["PER", "주가를 주당순이익과 비교하여 시장이 현재 이익을 얼마나 높게 평가하는지 보여줍니다."],
    priceToEarningsGrowthRatio: ["PEG", "PER을 예상 이익 성장률과 비교한 지표로, 값이 낮을수록 성장 대비 저평가되었다고 볼 수 있습니다."],
    returnOnEquity: ["자기자본이익률(ROE)", "자기자본을 얼마나 효율적으로 이익으로 전환하는지 보여줍니다."],
    returnOnInvestedCapital: ["투하자본이익률(ROIC)", "사업에 투입된 자본으로 얼마나 효율적으로 수익을 내는지 보여줍니다."],
    netProfitMargin: ["순이익률", "모든 비용, 이자, 세금을 차감한 뒤 순이익으로 남는 매출 비율입니다."],
    freeCashFlowYield: ["FCF 수익률", "잉여현금흐름을 시가총액과 비교하여 투자자가 얻을 수 있는 현금 수익률을 보여줍니다."],
    debtToEquityRatio: ["부채비율(D/E)", "총부채를 자기자본과 비교한 지표로, 높을수록 재무 레버리지가 큽니다."],
    currentRatio: ["유동비율", "유동자산을 유동부채와 비교하여 단기 지급 능력을 나타냅니다."],
    forwardPE: ["예상 PER", "주가를 다음 회계연도 예상 이익과 비교한 지표입니다."],
    priceToSalesRatio: ["PSR", "회사의 시가총액을 매출액과 비교한 지표입니다."],
    priceToBookRatio: ["PBR", "주가를 주당순자산과 비교한 지표입니다."],
    priceToFreeCashFlowRatio: ["주가FCF비율", "회계상 이익 대신 잉여현금흐름과 시가총액을 비교한 지표입니다."],
    priceToOperatingCashFlowRatio: ["주가영업CF비율", "시가총액을 영업활동으로 창출한 현금과 비교한 지표입니다."],
    enterpriseValueMultiple: ["EV/EBITDA", "기업가치를 EBITDA와 비교하여 자금조달과 비현금 비용을 배제한 밸류에이션을 평가합니다."],
    priceToFairValue: ["주가/적정가치", "현재 주가를 펀더멘털 기반 추정 적정가치와 비교한 지표입니다."],
    returnOnAssets: ["총자산이익률(ROA)", "보유 자산을 얼마나 효율적으로 이익 창출에 활용하는지 보여줍니다."],
    returnOnCapitalEmployed: ["ROCE", "자기자본과 부채를 합한 자본에서 영업이익을 얼마나 효율적으로 창출하는지 보여줍니다."],
    grossProfitMargin: ["매출총이익률", "직접 제조원가를 차감한 뒤 남는 매출 비율입니다."],
    operatingProfitMargin: ["영업이익률", "영업비용을 차감한 뒤 영업이익으로 남는 매출 비율입니다."],
    ebitdaMargin: ["EBITDA 마진", "이자, 세금, 감가상각비 차감 전 EBITDA가 매출에서 차지하는 비율입니다."],
    ebitMargin: ["EBIT 마진", "이자와 세금 차감 전 이익이 매출에서 차지하는 비율입니다."],
    pretaxProfitMargin: ["세전이익률", "세전이익이 매출에서 차지하는 비율입니다."],
    freeCashFlowMargin: ["FCF 마진", "설비투자 차감 후 잉여현금흐름이 매출에서 차지하는 비율입니다."],
    bottomLineProfitMargin: ["최종순이익률", "모든 비용과 세금을 차감한 최종 순이익이 매출에서 차지하는 비율입니다."],
    continuousOperationsProfitMargin: ["계속영업이익률", "중단사업을 제외한 계속영업 활동의 수익성입니다."],
    freeCashFlowPerShare: ["주당 FCF", "잉여현금흐름을 발행주식수로 나눈 값입니다."],
    revenuePerShare: ["주당 매출액", "매출액을 발행주식수로 나눈 값입니다."],
    netIncomePerShare: ["주당순이익(EPS)", "발행된 보통주 1주에 귀속되는 순이익입니다."],
    operatingCashFlowPerShare: ["주당 영업CF", "영업활동으로 창출한 현금을 발행주식수로 나눈 값입니다."],
    bookValuePerShare: ["주당순자산(BPS)", "자기자본을 발행주식수로 나눈 값입니다."],
    tangibleBookValuePerShare: ["주당 유형순자산", "영업권 등 무형자산을 제외한 주당순자산입니다."],
    cashPerShare: ["주당 현금", "현금 및 현금성자산을 발행주식수로 나눈 값입니다."],
    shareholdersEquityPerShare: ["주당 자기자본", "주주에게 귀속되는 자기자본을 발행주식수로 나눈 값입니다."],
    interestDebtPerShare: ["주당 이자부부채", "이자부부채를 발행주식수로 나눈 값입니다."],
    capexPerShare: ["주당 설비투자", "설비투자액을 발행주식수로 나눈 값입니다."],
    dividendYield: ["배당수익률", "주당 연간 배당금이 주가에서 차지하는 비율입니다."],
    dividendPerShare: ["주당배당금(DPS)", "지급된 총배당금을 발행주식수로 나눈 값입니다."],
    dividendPayoutRatio: ["배당성향", "이익 중 주주에게 배당으로 지급된 비율입니다."],
    dividendYieldPercentage: ["배당수익률 %", "연간 배당금이 주가 대비 차지하는 비율을 백분율로 나타낸 값입니다."],
    quickRatio: ["당좌비율", "재고자산을 제외한 유동자산을 유동부채와 비교한 지표입니다."],
    cashRatio: ["현금비율", "현금 및 현금성자산을 유동부채와 비교한 지표입니다."],
    debtToAssetsRatio: ["부채/총자산", "총자산 중 부채로 조달된 비율입니다."],
    debtToCapitalRatio: ["부채/총자본", "부채를 부채와 자기자본을 합한 총자본과 비교한 지표입니다."],
    longTermDebtToCapitalRatio: ["장기부채/총자본", "총자본 중 장기부채로 조달된 비율입니다."],
    debtToMarketCap: ["부채/시가총액", "총부채를 회사의 시가총액과 비교한 지표입니다."],
    financialLeverageRatio: ["재무레버리지", "자산 조달을 부채에 얼마나 의존하는지 보여줍니다."],
    solvencyRatio: ["지급여력비율", "장기 재무 의무를 이행할 수 있는 능력을 나타냅니다."],
    interestCoverageRatio: ["이자보상배율", "영업이익이 이자비용을 몇 배 감당할 수 있는지 보여줍니다."],
    operatingCashFlowRatio: ["영업CF비율", "영업현금흐름이 유동부채를 얼마나 감당하는지 보여줍니다."],
    operatingCashFlowSalesRatio: ["영업CF/매출액", "매출액이 영업현금흐름으로 얼마나 효율적으로 전환되는지 보여줍니다."],
    freeCashFlowOperatingCashFlowRatio: ["FCF/영업CF", "영업현금흐름 중 설비투자 후 잉여현금흐름으로 남는 비율입니다."],
    debtServiceCoverageRatio: ["부채상환커버리지", "영업이익이 원리금 상환을 얼마나 감당하는지 보여줍니다."],
    operatingCashFlowCoverageRatio: ["영업CF커버리지비율", "영업현금흐름이 총부채 의무를 얼마나 감당하는지 보여줍니다."],
    capitalExpenditureCoverageRatio: ["설비투자커버리지비율", "영업현금흐름이 설비투자를 얼마나 감당하는지 보여줍니다."],
    dividendPaidAndCapexCoverageRatio: ["배당 및 설비투자커버리지", "영업현금흐름이 배당과 설비투자를 모두 얼마나 감당하는지 보여줍니다."],
    shortTermOperatingCashFlowCoverageRatio: ["단기영업CF커버리지", "영업현금흐름이 단기 의무를 얼마나 감당하는지 보여줍니다."],
    assetTurnover: ["총자산회전율", "자산이 매출 창출에 얼마나 효율적으로 활용되는지 보여줍니다."],
    inventoryTurnover: ["재고자산회전율", "일정 기간 재고가 몇 번 판매되고 교체되었는지 보여줍니다."],
    receivablesTurnover: ["매출채권회전율", "외상매출금을 얼마나 효율적으로 회수하는지 보여줍니다."],
    payablesTurnover: ["매입채무회전율", "공급업체에 얼마나 빨리 대금을 지급하는지 보여줍니다."],
    fixedAssetTurnover: ["고정자산회전율", "고정자산이 매출 창출에 얼마나 효율적으로 활용되는지 보여줍니다."],
    workingCapitalTurnoverRatio: ["운전자본회전율", "운전자본이 매출 창출에 얼마나 효율적으로 활용되는지 보여줍니다."],
    effectiveTaxRate: ["실효세율", "세전이익에 대해 실제로 부담한 평균 세율입니다."],
    netIncomePerEBT: ["순이익/세전이익", "세전이익 중 세후 순이익으로 남는 비율입니다."],
    ebtPerEbit: ["세전이익/EBIT", "이자와 영업외 항목이 영업이익에 미치는 영향을 보여줍니다."],
  },
  seo: {
    title: "{company}({ticker}) 재무비율 및 밸류에이션 지표",
    description: "{company}({ticker})의 밸류에이션, 수익성, 유동성, 레버리지, 배당, 효율성 지표를 여러 기간에 걸쳐 확인하세요.",
    keywords: "{ticker} 재무비율, {company} 밸류에이션, PER, ROE, 부채비율, 수익성, 유동성, 배당수익률",
    name: "{company}({ticker}) 재무비율 분석",
    headline: "{company} 밸류에이션 및 재무지표",
    structuredDescription: "{company}({ticker})의 재무비율 분석으로 밸류에이션, 수익성, 유동성, 레버리지, 효율성을 다룹니다.",
    aboutName: "재무비율 분석",
    aboutDescription: "밸류에이션, 수익성, 유동성, 레버리지, 영업 효율성 분석입니다.",
    home: "홈",
    stocks: "주식",
    financialStatements: "재무제표",
    financialRatios: "재무비율",
  },
} satisfies FinancialRatiosSourceCatalog;
