import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "财务比率与指标",
  metrics: {
    priceToEarningsRatio: ["市盈率", "用股价除以每股收益，反映市场对公司当前盈利的估值水平。"],
    priceToEarningsGrowthRatio: ["PEG 比率", "将市盈率与预期盈利增速对比；数值较低可能意味着成长估值更便宜。"],
    returnOnEquity: ["净资产收益率", "衡量公司利用股东权益创造利润的效率。"],
    returnOnInvestedCapital: ["投入资本回报率", "衡量公司利用投入业务的资本创造回报的效率。"],
    netProfitMargin: ["净利率", "扣除全部成本、利息和税费后，净利润占营业收入的比例。"],
    freeCashFlowYield: ["自由现金流收益率", "将自由现金流与市值对比，反映投资者可获得的现金回报。"],
    debtToEquityRatio: ["负债权益比", "将总债务与股东权益对比；数值越高通常代表财务杠杆越大。"],
    currentRatio: ["流动比率", "将流动资产与流动负债对比，用于衡量短期偿债能力。"],
    forwardPE: ["预期市盈率", "用股价对比下一财年的预期每股收益。"],
    priceToSalesRatio: ["市销率", "将公司的市值与营业收入对比。"],
    priceToBookRatio: ["市净率", "将股价与每股净资产对比。"],
    priceToFreeCashFlowRatio: ["市值 / 自由现金流", "将市场价值与自由现金流对比，而不是与会计利润对比。"],
    priceToOperatingCashFlowRatio: ["市值 / 经营现金流", "将市场价值与经营活动产生的现金流对比。"],
    enterpriseValueMultiple: ["企业价值 / EBITDA", "将企业价值与 EBITDA 对比，便于排除融资结构和非现金费用的影响。"],
    priceToFairValue: ["价格 / 公允价值", "将当前股价与基于基本面估算的公允价值对比。"],
    returnOnAssets: ["总资产收益率", "衡量公司利用资产创造利润的效率。"],
    returnOnCapitalEmployed: ["资本回报率", "衡量公司利用股权和债务资本产生经营利润的效率。"],
    grossProfitMargin: ["毛利率", "扣除直接营业成本后，毛利润占营业收入的比例。"],
    operatingProfitMargin: ["营业利润率", "扣除经营费用后，营业利润占营业收入的比例。"],
    ebitdaMargin: ["EBITDA 利润率", "息税折旧摊销前利润占营业收入的比例。"],
    ebitMargin: ["EBIT 利润率", "息税前利润占营业收入的比例。"],
    pretaxProfitMargin: ["税前利润率", "税前利润占营业收入的比例。"],
    freeCashFlowMargin: ["自由现金流利润率", "扣除资本支出后，自由现金流占营业收入的比例。"],
    bottomLineProfitMargin: ["最终净利率", "扣除全部费用和税费后，最终净利润占营业收入的比例。"],
    continuousOperationsProfitMargin: ["持续经营利润率", "衡量持续经营业务的盈利能力，不包括已终止经营业务。"],
    freeCashFlowPerShare: ["每股自由现金流", "自由现金流除以流通股数。"],
    revenuePerShare: ["每股营业收入", "营业收入除以流通股数。"],
    netIncomePerShare: ["每股净利润", "归属于每股流通普通股的净利润。"],
    operatingCashFlowPerShare: ["每股经营现金流", "经营活动产生的现金流除以流通股数。"],
    bookValuePerShare: ["每股净资产", "股东权益除以流通股数。"],
    tangibleBookValuePerShare: ["每股有形净资产", "每股净资产扣除商誉和其他无形资产后的金额。"],
    cashPerShare: ["每股现金", "现金及现金等价物除以流通股数。"],
    shareholdersEquityPerShare: ["每股股东权益", "归属于股东的权益除以流通股数。"],
    interestDebtPerShare: ["每股有息债务", "有息债务除以流通股数。"],
    capexPerShare: ["每股资本支出", "资本支出除以流通股数。"],
    dividendYield: ["股息率", "每股年度股息占股价的比例。"],
    dividendPerShare: ["每股股息", "已支付股息总额除以流通股数。"],
    dividendPayoutRatio: ["股息支付率", "公司利润中用于向股东支付股息的比例。"],
    dividendYieldPercentage: ["股息率 %", "年度股息相对于股价的百分比。"],
    quickRatio: ["速动比率", "将不含存货的高流动性资产与流动负债对比。"],
    cashRatio: ["现金比率", "将现金及现金等价物与流动负债对比。"],
    debtToAssetsRatio: ["资产负债率", "反映公司资产中由债务融资的比例。"],
    debtToCapitalRatio: ["债务资本比", "将债务与总资本（债务加股东权益）对比。"],
    longTermDebtToCapitalRatio: ["长期债务资本比", "反映总资本中由长期债务融资的比例。"],
    debtToMarketCap: ["债务 / 市值", "将总债务与公司的股票市值对比。"],
    financialLeverageRatio: ["财务杠杆比率", "反映公司依赖债务为资产融资的程度。"],
    solvencyRatio: ["偿债能力比率", "反映公司履行长期财务义务的能力。"],
    interestCoverageRatio: ["利息保障倍数", "反映营业利润可覆盖利息费用的倍数。"],
    operatingCashFlowRatio: ["经营现金流比率", "反映经营现金流对流动负债的覆盖能力。"],
    operatingCashFlowSalesRatio: ["经营现金流 / 营业收入", "反映营业收入转化为经营现金流的效率。"],
    freeCashFlowOperatingCashFlowRatio: ["自由现金流 / 经营现金流", "反映资本支出后，经营现金流中剩余为自由现金流的比例。"],
    debtServiceCoverageRatio: ["债务偿付覆盖率", "反映经营利润对债务本息支付的覆盖能力。"],
    operatingCashFlowCoverageRatio: ["经营现金流覆盖率", "反映经营现金流对全部债务义务的覆盖能力。"],
    capitalExpenditureCoverageRatio: ["资本支出覆盖率", "反映经营现金流对资本支出的覆盖能力。"],
    dividendPaidAndCapexCoverageRatio: ["股息及资本支出覆盖率", "反映经营现金流对股息和资本支出的综合覆盖能力。"],
    shortTermOperatingCashFlowCoverageRatio: ["短期现金流覆盖率", "反映经营现金流对短期义务的覆盖能力。"],
    assetTurnover: ["总资产周转率", "衡量公司利用资产创造营业收入的效率。"],
    inventoryTurnover: ["存货周转率", "反映一段时期内存货售出并补充的频率。"],
    receivablesTurnover: ["应收账款周转率", "衡量公司收回应收账款的效率。"],
    payablesTurnover: ["应付账款周转率", "反映公司向供应商付款的速度。"],
    fixedAssetTurnover: ["固定资产周转率", "衡量公司利用固定资产创造营业收入的效率。"],
    workingCapitalTurnoverRatio: ["营运资本周转率", "衡量公司利用营运资本创造营业收入的效率。"],
    effectiveTaxRate: ["实际税率", "公司税前利润承担的平均税率。"],
    netIncomePerEBT: ["净利润 / 税前利润", "反映税前利润在纳税后转化为净利润的比例。"],
    ebtPerEbit: ["税前利润 / EBIT", "反映利息及非经营项目对营业利润的影响。"],
  },
  seo: {
    title: "{company}（{ticker}）财务比率与估值指标",
    description: "查看 {company}（{ticker}）多个时期的估值、盈利能力、流动性、杠杆、股息和运营效率指标。",
    keywords: "{ticker} 财务比率, {company} 估值, 市盈率, 净资产收益率, 负债权益比, 盈利能力, 流动性, 股息率",
    name: "{company}（{ticker}）财务比率分析",
    headline: "{company} 估值与财务指标",
    structuredDescription: "{company}（{ticker}）财务比率分析，涵盖估值、盈利能力、流动性、杠杆和运营效率。",
    aboutName: "财务比率分析",
    aboutDescription: "分析估值、盈利能力、流动性、杠杆和运营效率。",
    home: "首页",
    stocks: "股票",
    financialStatements: "财务报表",
    financialRatios: "财务比率",
  },
} satisfies FinancialRatiosSourceCatalog;
