import type { FinancialRatiosSourceCatalog } from "../types";

export default {
  sectionTitle: "財務比率與指標",
  metrics: {
    priceToEarningsRatio: ["本益比", "以股價除以每股盈餘，反映市場給予公司目前獲利的評價。"],
    priceToEarningsGrowthRatio: ["PEG 比率", "將本益比與預期盈餘成長率相比；數值較低可能代表成長估值較便宜。"],
    returnOnEquity: ["股東權益報酬率", "衡量公司運用股東權益創造獲利的效率。"],
    returnOnInvestedCapital: ["投入資本報酬率", "衡量公司運用投入營運的資本創造報酬的效率。"],
    netProfitMargin: ["稅後淨利率", "扣除所有成本、利息與稅負後，稅後淨利占營收的比率。"],
    freeCashFlowYield: ["自由現金流量殖利率", "將自由現金流量與市值相比，反映投資人可取得的現金報酬。"],
    debtToEquityRatio: ["負債對股東權益比", "將總負債與股東權益相比；數值越高通常表示財務槓桿越大。"],
    currentRatio: ["流動比率", "將流動資產與流動負債相比，用來衡量短期償債能力。"],
    forwardPE: ["預估本益比", "以股價對比下一會計年度的預估每股盈餘。"],
    priceToSalesRatio: ["股價營收比", "將公司的市場價值與營收相比。"],
    priceToBookRatio: ["股價淨值比", "將股價與每股淨值相比。"],
    priceToFreeCashFlowRatio: ["市值 / 自由現金流量", "將市場價值與自由現金流量相比，而非與會計盈餘相比。"],
    priceToOperatingCashFlowRatio: ["市值 / 營業現金流量", "將市場價值與營業活動產生的現金流量相比。"],
    enterpriseValueMultiple: ["企業價值 / EBITDA", "將企業價值與 EBITDA 相比，方便排除融資結構與非現金費用的影響。"],
    priceToFairValue: ["價格 / 公允價值", "將目前股價與依基本面估算的公允價值相比。"],
    returnOnAssets: ["資產報酬率", "衡量公司運用資產創造獲利的效率。"],
    returnOnCapitalEmployed: ["運用資本報酬率", "衡量公司運用股東資金與借款資本產生營業利益的效率。"],
    grossProfitMargin: ["毛利率", "扣除直接營業成本後，毛利占營收的比率。"],
    operatingProfitMargin: ["營業利益率", "扣除營業費用後，營業利益占營收的比率。"],
    ebitdaMargin: ["EBITDA 利潤率", "息稅折舊攤銷前利益占營收的比率。"],
    ebitMargin: ["EBIT 利潤率", "息前稅前利益占營收的比率。"],
    pretaxProfitMargin: ["稅前淨利率", "稅前淨利占營收的比率。"],
    freeCashFlowMargin: ["自由現金流量率", "扣除資本支出後，自由現金流量占營收的比率。"],
    bottomLineProfitMargin: ["最終淨利率", "扣除所有費用與稅負後，最終淨利占營收的比率。"],
    continuousOperationsProfitMargin: ["繼續營業部門淨利率", "衡量持續經營業務的獲利能力，不含停業部門。"],
    freeCashFlowPerShare: ["每股自由現金流量", "自由現金流量除以流通在外股數。"],
    revenuePerShare: ["每股營收", "營收除以流通在外股數。"],
    netIncomePerShare: ["每股稅後淨利", "歸屬於每股流通在外普通股的稅後淨利。"],
    operatingCashFlowPerShare: ["每股營業現金流量", "營業活動現金流量除以流通在外股數。"],
    bookValuePerShare: ["每股淨值", "股東權益除以流通在外股數。"],
    tangibleBookValuePerShare: ["每股有形淨值", "每股淨值扣除商譽及其他無形資產後的金額。"],
    cashPerShare: ["每股現金", "現金及約當現金除以流通在外股數。"],
    shareholdersEquityPerShare: ["每股股東權益", "歸屬股東的權益除以流通在外股數。"],
    interestDebtPerShare: ["每股計息負債", "需支付利息的負債除以流通在外股數。"],
    capexPerShare: ["每股資本支出", "資本支出除以流通在外股數。"],
    dividendYield: ["股利殖利率", "每股年度股利占股價的比率。"],
    dividendPerShare: ["每股股利", "已發放股利總額除以流通在外股數。"],
    dividendPayoutRatio: ["股利發放率", "公司盈餘中用來發放股利給股東的比率。"],
    dividendYieldPercentage: ["股利殖利率 %", "年度股利相對於股價的百分比。"],
    quickRatio: ["速動比率", "將不含存貨的高流動性資產與流動負債相比。"],
    cashRatio: ["現金比率", "將現金及約當現金與流動負債相比。"],
    debtToAssetsRatio: ["負債比率", "反映公司資產中由負債融通的比率。"],
    debtToCapitalRatio: ["負債對資本比", "將負債與總資本（負債加股東權益）相比。"],
    longTermDebtToCapitalRatio: ["長期負債對資本比", "反映總資本中由長期負債融通的比率。"],
    debtToMarketCap: ["負債 / 市值", "將總負債與公司的股票市值相比。"],
    financialLeverageRatio: ["財務槓桿比率", "反映公司依賴負債為資產融通的程度。"],
    solvencyRatio: ["長期償債能力比率", "反映公司履行長期財務義務的能力。"],
    interestCoverageRatio: ["利息保障倍數", "反映營業利益可支付利息費用的倍數。"],
    operatingCashFlowRatio: ["營業現金流量比率", "反映營業現金流量對流動負債的保障能力。"],
    operatingCashFlowSalesRatio: ["營業現金流量 / 營收", "反映營收轉換為營業現金流量的效率。"],
    freeCashFlowOperatingCashFlowRatio: ["自由現金流量 / 營業現金流量", "反映扣除資本支出後，營業現金流量中剩餘為自由現金流量的比率。"],
    debtServiceCoverageRatio: ["債務償付保障倍數", "反映營業利益對債務本金與利息支出的保障能力。"],
    operatingCashFlowCoverageRatio: ["營業現金流量保障比率", "反映營業現金流量對全部債務義務的保障能力。"],
    capitalExpenditureCoverageRatio: ["資本支出保障比率", "反映營業現金流量對資本支出的保障能力。"],
    dividendPaidAndCapexCoverageRatio: ["股利及資本支出保障比率", "反映營業現金流量對股利和資本支出的綜合保障能力。"],
    shortTermOperatingCashFlowCoverageRatio: ["短期現金流量保障比率", "反映營業現金流量對短期義務的保障能力。"],
    assetTurnover: ["總資產週轉率", "衡量公司運用資產創造營收的效率。"],
    inventoryTurnover: ["存貨週轉率", "反映一段期間內存貨售出並補充的頻率。"],
    receivablesTurnover: ["應收帳款週轉率", "衡量公司收回信用銷售款項的效率。"],
    payablesTurnover: ["應付帳款週轉率", "反映公司向供應商付款的速度。"],
    fixedAssetTurnover: ["固定資產週轉率", "衡量公司運用固定資產創造營收的效率。"],
    workingCapitalTurnoverRatio: ["營運資金週轉率", "衡量公司運用營運資金創造營收的效率。"],
    effectiveTaxRate: ["有效稅率", "公司稅前淨利實際負擔的平均稅率。"],
    netIncomePerEBT: ["稅後淨利 / 稅前淨利", "反映稅前淨利在繳稅後轉換為稅後淨利的比率。"],
    ebtPerEbit: ["稅前淨利 / EBIT", "反映利息及非營業項目對營業利益的影響。"],
  },
  seo: {
    title: "{company}（{ticker}）財務比率與估值指標",
    description: "查看 {company}（{ticker}）多個期間的估值、獲利能力、流動性、槓桿、股利與營運效率指標。",
    keywords: "{ticker} 財務比率, {company} 估值, 本益比, 股東權益報酬率, 負債對股東權益比, 獲利能力, 流動性, 股利殖利率",
    name: "{company}（{ticker}）財務比率分析",
    headline: "{company} 估值與財務指標",
    structuredDescription: "{company}（{ticker}）財務比率分析，涵蓋估值、獲利能力、流動性、財務槓桿與營運效率。",
    aboutName: "財務比率分析",
    aboutDescription: "分析估值、獲利能力、流動性、財務槓桿與營運效率。",
    home: "首頁",
    stocks: "股票",
    financialStatements: "財務報表",
    financialRatios: "財務比率",
  },
} satisfies FinancialRatiosSourceCatalog;
