export type StatementIndicatorTab = "income" | "balance" | "cashflow" | "ratios";
export type StatementIndicatorFormat = "currency" | "number" | "percent";

export type StatementIndicatorConfig = {
  id: string;
  label: string;
  statement: StatementIndicatorTab;
  property: string;
  format: StatementIndicatorFormat;
  infoKey?: string;
};

export const STATEMENT_INDICATORS: StatementIndicatorConfig[] = [
  {
    id: "income_costOfRevenue",
    label: "Cost of Revenue",
    statement: "income",
    property: "costOfRevenue",
    format: "currency",
  },
  {
    id: "income_grossProfit",
    label: "Gross Profit",
    statement: "income",
    property: "grossProfit",
    format: "currency",
  },
  {
    id: "income_operatingIncome",
    label: "Operating Income",
    statement: "income",
    property: "operatingIncome",
    format: "currency",
  },
  {
    id: "income_interestIncome",
    label: "Interest Income",
    statement: "income",
    property: "interestIncome",
    format: "currency",
  },
  {
    id: "income_incomeBeforeTax",
    label: "Pretax Income",
    statement: "income",
    property: "incomeBeforeTax",
    format: "currency",
  },
  {
    id: "income_netIncome",
    label: "Net Income",
    statement: "income",
    property: "netIncome",
    format: "currency",
  },
  {
    id: "income_sellingGeneralAndAdministrativeExpenses",
    label: "Selling & General & Admin",
    statement: "income",
    property: "sellingGeneralAndAdministrativeExpenses",
    format: "currency",
  },
  {
    id: "income_researchAndDevelopmentExpenses",
    label: "Research & Development",
    statement: "income",
    property: "researchAndDevelopmentExpenses",
    format: "currency",
  },
  {
    id: "income_otherExpenses",
    label: "Other Expenses",
    statement: "income",
    property: "otherExpenses",
    format: "currency",
  },
  {
    id: "income_operatingExpenses",
    label: "Operating Expenses",
    statement: "income",
    property: "operatingExpenses",
    format: "currency",
  },
  {
    id: "income_interestExpense",
    label: "Interest Expense",
    statement: "income",
    property: "interestExpense",
    format: "currency",
  },
  {
    id: "income_sellingAndMarketingExpenses",
    label: "Selling & Marketing Expenses",
    statement: "income",
    property: "sellingAndMarketingExpenses",
    format: "currency",
  },
  {
    id: "income_costAndExpenses",
    label: "Cost & Expenses",
    statement: "income",
    property: "costAndExpenses",
    format: "currency",
  },
  {
    id: "income_incomeTaxExpense",
    label: "Income Tax Expense",
    statement: "income",
    property: "incomeTaxExpense",
    format: "currency",
  },
  {
    id: "income_weightedAverageShsOut",
    label: "Shares Outstanding (Basic)",
    statement: "income",
    property: "weightedAverageShsOut",
    format: "number",
  },
  {
    id: "income_weightedAverageShsOutDil",
    label: "Shares Outstanding (Diluted)",
    statement: "income",
    property: "weightedAverageShsOutDil",
    format: "number",
  },
  {
    id: "income_epsDiluted",
    label: "EPS (Diluted)",
    statement: "income",
    property: "epsDiluted",
    format: "currency",
  },
  {
    id: "income_ebitda",
    label: "EBITDA",
    statement: "income",
    property: "ebitda",
    format: "currency",
  },
  {
    id: "income_ebit",
    label: "EBIT",
    statement: "income",
    property: "ebit",
    format: "currency",
  },
  {
    id: "income_depreciationAndAmortization",
    label: "Depreciation & Amortization",
    statement: "income",
    property: "depreciationAndAmortization",
    format: "currency",
  },
  {
    id: "balance_cashAndCashEquivalents",
    label: "Cash & Equivalents",
    statement: "balance",
    property: "cashAndCashEquivalents",
    format: "currency",
  },
  {
    id: "balance_shortTermInvestments",
    label: "Short-Term Investments",
    statement: "balance",
    property: "shortTermInvestments",
    format: "currency",
  },
  {
    id: "balance_cashAndShortTermInvestments",
    label: "Cash & Short-Term Investments",
    statement: "balance",
    property: "cashAndShortTermInvestments",
    format: "currency",
  },
  {
    id: "balance_netReceivables",
    label: "Receivables",
    statement: "balance",
    property: "netReceivables",
    format: "currency",
  },
  {
    id: "balance_accountsReceivables",
    label: "Accounts Receivables",
    statement: "balance",
    property: "accountsReceivables",
    format: "currency",
  },
  {
    id: "balance_otherReceivables",
    label: "Other Receivables",
    statement: "balance",
    property: "otherReceivables",
    format: "currency",
  },
  {
    id: "balance_inventory",
    label: "Inventory",
    statement: "balance",
    property: "inventory",
    format: "currency",
  },
  {
    id: "balance_prepaids",
    label: "Prepaid Expenses",
    statement: "balance",
    property: "prepaids",
    format: "currency",
  },
  {
    id: "balance_otherCurrentAssets",
    label: "Other Current Assets",
    statement: "balance",
    property: "otherCurrentAssets",
    format: "currency",
  },
  {
    id: "balance_totalCurrentAssets",
    label: "Total Current Assets",
    statement: "balance",
    property: "totalCurrentAssets",
    format: "currency",
  },
  {
    id: "balance_propertyPlantEquipmentNet",
    label: "Property-Plant & Equipment",
    statement: "balance",
    property: "propertyPlantEquipmentNet",
    format: "currency",
  },
  {
    id: "balance_goodwill",
    label: "Goodwill",
    statement: "balance",
    property: "goodwill",
    format: "currency",
  },
  {
    id: "balance_intangibleAssets",
    label: "Intangible Assets",
    statement: "balance",
    property: "intangibleAssets",
    format: "currency",
  },
  {
    id: "balance_goodwillAndIntangibleAssets",
    label: "Goodwill & Intangibles",
    statement: "balance",
    property: "goodwillAndIntangibleAssets",
    format: "currency",
  },
  {
    id: "balance_longTermInvestments",
    label: "Long-Term Investments",
    statement: "balance",
    property: "longTermInvestments",
    format: "currency",
  },
  {
    id: "balance_taxAssets",
    label: "Tax Assets",
    statement: "balance",
    property: "taxAssets",
    format: "currency",
  },
  {
    id: "balance_otherNonCurrentAssets",
    label: "Other Long-Term Assets",
    statement: "balance",
    property: "otherNonCurrentAssets",
    format: "currency",
  },
  {
    id: "balance_totalNonCurrentAssets",
    label: "Total Long-Term Assets",
    statement: "balance",
    property: "totalNonCurrentAssets",
    format: "currency",
  },
  {
    id: "balance_otherAssets",
    label: "Other Assets",
    statement: "balance",
    property: "otherAssets",
    format: "currency",
  },
  {
    id: "balance_totalAssets",
    label: "Total Assets",
    statement: "balance",
    property: "totalAssets",
    format: "currency",
  },
  {
    id: "balance_totalPayables",
    label: "Total Payables",
    statement: "balance",
    property: "totalPayables",
    format: "currency",
  },
  {
    id: "balance_accountPayables",
    label: "Account Payables",
    statement: "balance",
    property: "accountPayables",
    format: "currency",
  },
  {
    id: "balance_otherPayables",
    label: "Other Payables",
    statement: "balance",
    property: "otherPayables",
    format: "currency",
  },
  {
    id: "balance_accruedExpenses",
    label: "Accrued Expenses",
    statement: "balance",
    property: "accruedExpenses",
    format: "currency",
  },
  {
    id: "balance_shortTermDebt",
    label: "Short-Term Debt",
    statement: "balance",
    property: "shortTermDebt",
    format: "currency",
  },
  {
    id: "balance_capitalLeaseObligationsCurrent",
    label: "Current Capital Lease Obligations",
    statement: "balance",
    property: "capitalLeaseObligationsCurrent",
    format: "currency",
  },
  {
    id: "balance_taxPayables",
    label: "Tax Payables",
    statement: "balance",
    property: "taxPayables",
    format: "currency",
  },
  {
    id: "balance_deferredRevenue",
    label: "Deferred Revenue",
    statement: "balance",
    property: "deferredRevenue",
    format: "currency",
  },
  {
    id: "balance_otherCurrentLiabilities",
    label: "Other Current Liabilities",
    statement: "balance",
    property: "otherCurrentLiabilities",
    format: "currency",
  },
  {
    id: "balance_totalCurrentLiabilities",
    label: "Total Current Liabilities",
    statement: "balance",
    property: "totalCurrentLiabilities",
    format: "currency",
  },
  {
    id: "balance_longTermDebt",
    label: "Long-Term Debt",
    statement: "balance",
    property: "longTermDebt",
    format: "currency",
  },
  {
    id: "balance_capitalLeaseObligationsNonCurrent",
    label: "Non-Current Capital Lease Obligations",
    statement: "balance",
    property: "capitalLeaseObligationsNonCurrent",
    format: "currency",
  },
  {
    id: "balance_deferredRevenueNonCurrent",
    label: "Non-Current Deferred Revenue",
    statement: "balance",
    property: "deferredRevenueNonCurrent",
    format: "currency",
  },
  {
    id: "balance_deferredTaxLiabilitiesNonCurrent",
    label: "Non-Current Deferred Tax Liabilities",
    statement: "balance",
    property: "deferredTaxLiabilitiesNonCurrent",
    format: "currency",
  },
  {
    id: "balance_otherNonCurrentLiabilities",
    label: "Other Long-Term Liabilities",
    statement: "balance",
    property: "otherNonCurrentLiabilities",
    format: "currency",
  },
  {
    id: "balance_totalNonCurrentLiabilities",
    label: "Total Long-Term Liabilities",
    statement: "balance",
    property: "totalNonCurrentLiabilities",
    format: "currency",
  },
  {
    id: "balance_otherLiabilities",
    label: "Other Liabilities",
    statement: "balance",
    property: "otherLiabilities",
    format: "currency",
  },
  {
    id: "balance_capitalLeaseObligations",
    label: "Capital Lease Obligations",
    statement: "balance",
    property: "capitalLeaseObligations",
    format: "currency",
  },
  {
    id: "balance_totalLiabilities",
    label: "Total Liabilities",
    statement: "balance",
    property: "totalLiabilities",
    format: "currency",
  },
  {
    id: "balance_treasuryStock",
    label: "Treasury Stock",
    statement: "balance",
    property: "treasuryStock",
    format: "currency",
  },
  {
    id: "balance_preferredStock",
    label: "Preferred Stock",
    statement: "balance",
    property: "preferredStock",
    format: "currency",
  },
  {
    id: "balance_commonStock",
    label: "Common Stock",
    statement: "balance",
    property: "commonStock",
    format: "currency",
  },
  {
    id: "balance_retainedEarnings",
    label: "Retained Earnings",
    statement: "balance",
    property: "retainedEarnings",
    format: "currency",
  },
  {
    id: "balance_additionalPaidInCapital",
    label: "Additional Paid-In Capital",
    statement: "balance",
    property: "additionalPaidInCapital",
    format: "currency",
  },
  {
    id: "balance_accumulatedOtherComprehensiveIncomeLoss",
    label: "Comprehensive Income",
    statement: "balance",
    property: "accumulatedOtherComprehensiveIncomeLoss",
    format: "currency",
  },
  {
    id: "balance_otherTotalStockholdersEquity",
    label: "Other Stockholders Equity",
    statement: "balance",
    property: "otherTotalStockholdersEquity",
    format: "currency",
  },
  {
    id: "balance_totalStockholdersEquity",
    label: "Shareholders Equity",
    statement: "balance",
    property: "totalStockholdersEquity",
    format: "currency",
  },
  {
    id: "balance_totalEquity",
    label: "Total Equity",
    statement: "balance",
    property: "totalEquity",
    format: "currency",
  },
  {
    id: "balance_minorityInterest",
    label: "Minority Interest",
    statement: "balance",
    property: "minorityInterest",
    format: "currency",
  },
  {
    id: "balance_totalLiabilitiesAndTotalEquity",
    label: "Total Liabilities & Equity",
    statement: "balance",
    property: "totalLiabilitiesAndTotalEquity",
    format: "currency",
  },
  {
    id: "balance_totalInvestments",
    label: "Total Investments",
    statement: "balance",
    property: "totalInvestments",
    format: "currency",
  },
  {
    id: "balance_totalDebt",
    label: "Total Debt",
    statement: "balance",
    property: "totalDebt",
    format: "currency",
  },
  {
    id: "balance_netDebt",
    label: "Net Debt",
    statement: "balance",
    property: "netDebt",
    format: "currency",
  },
  {
    id: "balance_bookValue",
    label: "Book Value",
    statement: "balance",
    property: "bookValue",
    format: "currency",
  },
  {
    id: "balance_bookValuePerShare",
    label: "Book Value Per Share",
    statement: "balance",
    property: "bookValuePerShare",
    format: "currency",
  },
  {
    id: "cashflow_netIncome",
    label: "Net Income",
    statement: "cashflow",
    property: "netIncome",
    format: "currency",
  },
  {
    id: "cashflow_depreciationAndAmortization",
    label: "Depreciation & Amortization",
    statement: "cashflow",
    property: "depreciationAndAmortization",
    format: "currency",
  },
  {
    id: "cashflow_deferredIncomeTax",
    label: "Deferred Income Tax",
    statement: "cashflow",
    property: "deferredIncomeTax",
    format: "currency",
  },
  {
    id: "cashflow_stockBasedCompensation",
    label: "Stock-Based Compensation",
    statement: "cashflow",
    property: "stockBasedCompensation",
    format: "currency",
  },
  {
    id: "cashflow_changeInWorkingCapital",
    label: "Change in Working Capital",
    statement: "cashflow",
    property: "changeInWorkingCapital",
    format: "currency",
  },
  {
    id: "cashflow_accountsReceivables",
    label: "Accounts Receivables",
    statement: "cashflow",
    property: "accountsReceivables",
    format: "currency",
  },
  {
    id: "cashflow_inventory",
    label: "Inventory",
    statement: "cashflow",
    property: "inventory",
    format: "currency",
  },
  {
    id: "cashflow_accountsPayables",
    label: "Accounts Payables",
    statement: "cashflow",
    property: "accountsPayables",
    format: "currency",
  },
  {
    id: "cashflow_otherWorkingCapital",
    label: "Other Working Capital",
    statement: "cashflow",
    property: "otherWorkingCapital",
    format: "currency",
  },
  {
    id: "cashflow_otherNonCashItems",
    label: "Other Non-Cash Items",
    statement: "cashflow",
    property: "otherNonCashItems",
    format: "currency",
  },
  {
    id: "cashflow_netCashProvidedByOperatingActivities",
    label: "Net Cash from Operating Activities",
    statement: "cashflow",
    property: "netCashProvidedByOperatingActivities",
    format: "currency",
  },
  {
    id: "cashflow_operatingCashFlow",
    label: "Operating Cash Flow",
    statement: "cashflow",
    property: "operatingCashFlow",
    format: "currency",
  },
  {
    id: "cashflow_investmentsInPropertyPlantAndEquipment",
    label: "PP&E Investments",
    statement: "cashflow",
    property: "investmentsInPropertyPlantAndEquipment",
    format: "currency",
  },
  {
    id: "cashflow_capitalExpenditure",
    label: "Capital Expenditures",
    statement: "cashflow",
    property: "capitalExpenditure",
    format: "currency",
  },
  {
    id: "cashflow_acquisitionsNet",
    label: "Cash Acquisitions",
    statement: "cashflow",
    property: "acquisitionsNet",
    format: "currency",
  },
  {
    id: "cashflow_purchasesOfInvestments",
    label: "Purchase of Investments",
    statement: "cashflow",
    property: "purchasesOfInvestments",
    format: "currency",
  },
  {
    id: "cashflow_salesMaturitiesOfInvestments",
    label: "Sales Maturities of Investments",
    statement: "cashflow",
    property: "salesMaturitiesOfInvestments",
    format: "currency",
  },
  {
    id: "cashflow_otherInvestingActivities",
    label: "Other Investing Activities",
    statement: "cashflow",
    property: "otherInvestingActivities",
    format: "currency",
  },
  {
    id: "cashflow_netCashProvidedByInvestingActivities",
    label: "Net Cash from Investing Activities",
    statement: "cashflow",
    property: "netCashProvidedByInvestingActivities",
    format: "currency",
  },
  {
    id: "cashflow_netDebtIssuance",
    label: "Net Debt Issuance",
    statement: "cashflow",
    property: "netDebtIssuance",
    format: "currency",
  },
  {
    id: "cashflow_longTermNetDebtIssuance",
    label: "Long-Term Net Debt Issuance",
    statement: "cashflow",
    property: "longTermNetDebtIssuance",
    format: "currency",
  },
  {
    id: "cashflow_shortTermNetDebtIssuance",
    label: "Short-Term Net Debt Issuance",
    statement: "cashflow",
    property: "shortTermNetDebtIssuance",
    format: "currency",
  },
  {
    id: "cashflow_netStockIssuance",
    label: "Net Stock Issuance",
    statement: "cashflow",
    property: "netStockIssuance",
    format: "currency",
  },
  {
    id: "cashflow_netCommonStockIssuance",
    label: "Net Common Stock Issuance",
    statement: "cashflow",
    property: "netCommonStockIssuance",
    format: "currency",
  },
  {
    id: "cashflow_commonStockIssuance",
    label: "Common Stock Issuance",
    statement: "cashflow",
    property: "commonStockIssuance",
    format: "currency",
  },
  {
    id: "cashflow_commonStockRepurchased",
    label: "Common Stock Repurchased",
    statement: "cashflow",
    property: "commonStockRepurchased",
    format: "currency",
  },
  {
    id: "cashflow_netPreferredStockIssuance",
    label: "Net Preferred Stock Issuance",
    statement: "cashflow",
    property: "netPreferredStockIssuance",
    format: "currency",
  },
  {
    id: "cashflow_netDividendsPaid",
    label: "Net Dividends Paid",
    statement: "cashflow",
    property: "netDividendsPaid",
    format: "currency",
  },
  {
    id: "cashflow_commonDividendsPaid",
    label: "Common Dividends Paid",
    statement: "cashflow",
    property: "commonDividendsPaid",
    format: "currency",
  },
  {
    id: "cashflow_preferredDividendsPaid",
    label: "Preferred Dividends Paid",
    statement: "cashflow",
    property: "preferredDividendsPaid",
    format: "currency",
  },
  {
    id: "cashflow_otherFinancingActivities",
    label: "Other Financing Activities",
    statement: "cashflow",
    property: "otherFinancingActivities",
    format: "currency",
  },
  {
    id: "cashflow_netCashProvidedByFinancingActivities",
    label: "Net Cash from Financing Activities",
    statement: "cashflow",
    property: "netCashProvidedByFinancingActivities",
    format: "currency",
  },
  {
    id: "cashflow_effectOfForexChangesOnCash",
    label: "Effect of Forex Changes on Cash",
    statement: "cashflow",
    property: "effectOfForexChangesOnCash",
    format: "currency",
  },
  {
    id: "cashflow_netChangeInCash",
    label: "Net Change in Cash",
    statement: "cashflow",
    property: "netChangeInCash",
    format: "currency",
  },
  {
    id: "cashflow_cashAtEndOfPeriod",
    label: "Cash at End of Period",
    statement: "cashflow",
    property: "cashAtEndOfPeriod",
    format: "currency",
  },
  {
    id: "cashflow_cashAtBeginningOfPeriod",
    label: "Cash at Beginning of Period",
    statement: "cashflow",
    property: "cashAtBeginningOfPeriod",
    format: "currency",
  },
  {
    id: "cashflow_incomeTaxesPaid",
    label: "Income Taxes Paid",
    statement: "cashflow",
    property: "incomeTaxesPaid",
    format: "currency",
  },
  {
    id: "cashflow_interestPaid",
    label: "Interest Paid",
    statement: "cashflow",
    property: "interestPaid",
    format: "currency",
  },
  {
    id: "ratio_forwardPE",
    label: "Forward PE Ratio",
    statement: "ratios",
    property: "forwardPE",
    format: "number",
  },
  {
    id: "ratio_priceToEarningsGrowthRatio",
    label: "PEG Ratio",
    statement: "ratios",
    property: "priceToEarningsGrowthRatio",
    format: "number",
  },
  {
    id: "ratio_priceToSalesRatio",
    label: "PS Ratio",
    statement: "ratios",
    property: "priceToSalesRatio",
    format: "number",
  },
  {
    id: "ratio_priceToBookRatio",
    label: "PB Ratio",
    statement: "ratios",
    property: "priceToBookRatio",
    format: "number",
  },
  {
    id: "ratio_priceToFreeCashFlowRatio",
    label: "P/FCF Ratio",
    statement: "ratios",
    property: "priceToFreeCashFlowRatio",
    format: "number",
  },
  {
    id: "ratio_priceToOperatingCashFlowRatio",
    label: "P/OCF Ratio",
    statement: "ratios",
    property: "priceToOperatingCashFlowRatio",
    format: "number",
  },
  {
    id: "ratio_priceToFairValue",
    label: "Price to Fair Value",
    statement: "ratios",
    property: "priceToFairValue",
    format: "number",
  },
  {
    id: "ratio_freeCashFlowYield",
    label: "FCF Yield",
    statement: "ratios",
    property: "freeCashFlowYield",
    format: "percent",
  },
  {
    id: "ratio_returnOnEquity",
    label: "Return on Equity",
    statement: "ratios",
    property: "returnOnEquity",
    format: "percent",
  },
  {
    id: "ratio_returnOnAssets",
    label: "Return on Assets",
    statement: "ratios",
    property: "returnOnAssets",
    format: "percent",
  },
  {
    id: "ratio_returnOnInvestedCapital",
    label: "Return on Invested Capital",
    statement: "ratios",
    property: "returnOnInvestedCapital",
    format: "percent",
  },
  {
    id: "ratio_returnOnCapitalEmployed",
    label: "Return on Capital Employed",
    statement: "ratios",
    property: "returnOnCapitalEmployed",
    format: "percent",
  },
  {
    id: "ratio_grossProfitMargin",
    label: "Gross Profit Margin",
    statement: "ratios",
    property: "grossProfitMargin",
    format: "percent",
  },
  {
    id: "ratio_operatingProfitMargin",
    label: "Operating Profit Margin",
    statement: "ratios",
    property: "operatingProfitMargin",
    format: "percent",
  },
  {
    id: "ratio_ebitMargin",
    label: "EBIT Margin",
    statement: "ratios",
    property: "ebitMargin",
    format: "percent",
  },
  {
    id: "ratio_ebitdaMargin",
    label: "EBITDA Margin",
    statement: "ratios",
    property: "ebitdaMargin",
    format: "percent",
  },
  {
    id: "ratio_pretaxProfitMargin",
    label: "Pretax Profit Margin",
    statement: "ratios",
    property: "pretaxProfitMargin",
    format: "percent",
  },
  {
    id: "ratio_bottomLineProfitMargin",
    label: "Bottom Line Profit Margin",
    statement: "ratios",
    property: "bottomLineProfitMargin",
    format: "percent",
  },
  {
    id: "ratio_continuousOperationsProfitMargin",
    label: "Continuous Operations Margin",
    statement: "ratios",
    property: "continuousOperationsProfitMargin",
    format: "percent",
  },
  {
    id: "ratio_freeCashFlowMargin",
    label: "FCF Margin",
    statement: "ratios",
    property: "freeCashFlowMargin",
    format: "percent",
  },
  {
    id: "ratio_operatingCashFlowRatio",
    label: "OCF Ratio",
    statement: "ratios",
    property: "operatingCashFlowRatio",
    format: "number",
  },
  {
    id: "ratio_operatingCashFlowSalesRatio",
    label: "OCF/S Ratio",
    statement: "ratios",
    property: "operatingCashFlowSalesRatio",
    format: "number",
  },
  {
    id: "ratio_freeCashFlowOperatingCashFlowRatio",
    label: "FCF/OCF Ratio",
    statement: "ratios",
    property: "freeCashFlowOperatingCashFlowRatio",
    format: "number",
  },
  {
    id: "ratio_shortTermOperatingCashFlowCoverageRatio",
    label: "ST OCF Coverage",
    statement: "ratios",
    property: "shortTermOperatingCashFlowCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_operatingCashFlowCoverageRatio",
    label: "OCF Coverage Ratio",
    statement: "ratios",
    property: "operatingCashFlowCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_capitalExpenditureCoverageRatio",
    label: "CapEx Coverage Ratio",
    statement: "ratios",
    property: "capitalExpenditureCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_dividendPaidAndCapexCoverageRatio",
    label: "Dividend & CapEx Coverage",
    statement: "ratios",
    property: "dividendPaidAndCapexCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_interestCoverageRatio",
    label: "Interest Coverage",
    statement: "ratios",
    property: "interestCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_debtServiceCoverageRatio",
    label: "Debt Service Coverage",
    statement: "ratios",
    property: "debtServiceCoverageRatio",
    format: "number",
  },
  {
    id: "ratio_assetTurnover",
    label: "Asset Turnover",
    statement: "ratios",
    property: "assetTurnover",
    format: "number",
  },
  {
    id: "ratio_fixedAssetTurnover",
    label: "Fixed Asset Turnover",
    statement: "ratios",
    property: "fixedAssetTurnover",
    format: "number",
  },
  {
    id: "ratio_workingCapitalTurnoverRatio",
    label: "Working Capital Turnover",
    statement: "ratios",
    property: "workingCapitalTurnoverRatio",
    format: "number",
  },
  {
    id: "ratio_receivablesTurnover",
    label: "Receivables Turnover",
    statement: "ratios",
    property: "receivablesTurnover",
    format: "number",
  },
  {
    id: "ratio_payablesTurnover",
    label: "Payables Turnover",
    statement: "ratios",
    property: "payablesTurnover",
    format: "number",
  },
  {
    id: "ratio_inventoryTurnover",
    label: "Inventory Turnover",
    statement: "ratios",
    property: "inventoryTurnover",
    format: "number",
  },
  {
    id: "ratio_debtToEquityRatio",
    label: "Debt / Equity Ratio",
    statement: "ratios",
    property: "debtToEquityRatio",
    format: "number",
  },
  {
    id: "ratio_debtToAssetsRatio",
    label: "Debt to Assets Ratio",
    statement: "ratios",
    property: "debtToAssetsRatio",
    format: "number",
  },
  {
    id: "ratio_debtToCapitalRatio",
    label: "Debt to Capital Ratio",
    statement: "ratios",
    property: "debtToCapitalRatio",
    format: "number",
  },
  {
    id: "ratio_longTermDebtToCapitalRatio",
    label: "LT Debt to Capital Ratio",
    statement: "ratios",
    property: "longTermDebtToCapitalRatio",
    format: "number",
  },
  {
    id: "ratio_debtToMarketCap",
    label: "Debt to Market Cap",
    statement: "ratios",
    property: "debtToMarketCap",
    format: "number",
  },
  {
    id: "ratio_financialLeverageRatio",
    label: "Financial Leverage Ratio",
    statement: "ratios",
    property: "financialLeverageRatio",
    format: "number",
  },
  {
    id: "ratio_solvencyRatio",
    label: "Solvency Ratio",
    statement: "ratios",
    property: "solvencyRatio",
    format: "number",
  },
  {
    id: "ratio_currentRatio",
    label: "Current Ratio",
    statement: "ratios",
    property: "currentRatio",
    format: "number",
  },
  {
    id: "ratio_quickRatio",
    label: "Quick Ratio",
    statement: "ratios",
    property: "quickRatio",
    format: "number",
  },
  {
    id: "ratio_cashRatio",
    label: "Cash Ratio",
    statement: "ratios",
    property: "cashRatio",
    format: "number",
  },
  {
    id: "ratio_revenuePerShare",
    label: "Revenue Per Share",
    statement: "ratios",
    property: "revenuePerShare",
    format: "number",
  },
  {
    id: "ratio_netIncomePerShare",
    label: "Net Income Per Share",
    statement: "ratios",
    property: "netIncomePerShare",
    format: "number",
  },
  {
    id: "ratio_operatingCashFlowPerShare",
    label: "Operating Cash Flow Per Share",
    statement: "ratios",
    property: "operatingCashFlowPerShare",
    format: "number",
  },
  {
    id: "ratio_freeCashFlowPerShare",
    label: "Free Cash Flow Per Share",
    statement: "ratios",
    property: "freeCashFlowPerShare",
    format: "number",
  },
  {
    id: "ratio_cashPerShare",
    label: "Cash Per Share",
    statement: "ratios",
    property: "cashPerShare",
    format: "number",
  },
  {
    id: "ratio_bookValuePerShare",
    label: "Book Value Per Share",
    statement: "ratios",
    property: "bookValuePerShare",
    format: "number",
  },
  {
    id: "ratio_tangibleBookValuePerShare",
    label: "Tangible Book Value Per Share",
    statement: "ratios",
    property: "tangibleBookValuePerShare",
    format: "number",
  },
  {
    id: "ratio_shareholdersEquityPerShare",
    label: "Shareholders' Equity Per Share",
    statement: "ratios",
    property: "shareholdersEquityPerShare",
    format: "number",
  },
  {
    id: "ratio_interestDebtPerShare",
    label: "Interest Debt Per Share",
    statement: "ratios",
    property: "interestDebtPerShare",
    format: "number",
  },
  {
    id: "ratio_capexPerShare",
    label: "CapEx Per Share",
    statement: "ratios",
    property: "capexPerShare",
    format: "number",
  },
  {
    id: "ratio_dividendPerShare",
    label: "Dividend Per Share",
    statement: "ratios",
    property: "dividendPerShare",
    format: "number",
  },
  {
    id: "ratio_dividendYield",
    label: "Dividend Yield",
    statement: "ratios",
    property: "dividendYield",
    format: "percent",
  },
  {
    id: "ratio_dividendYieldPercentage",
    label: "Dividend Yield %",
    statement: "ratios",
    property: "dividendYieldPercentage",
    format: "percent",
  },
  {
    id: "ratio_dividendPayoutRatio",
    label: "Payout Ratio",
    statement: "ratios",
    property: "dividendPayoutRatio",
    format: "number",
  },
  {
    id: "ratio_netIncomePerEBT",
    label: "Net Income / EBT",
    statement: "ratios",
    property: "netIncomePerEBT",
    format: "number",
  },
  {
    id: "ratio_ebtPerEbit",
    label: "EBT / EBIT",
    statement: "ratios",
    property: "ebtPerEbit",
    format: "number",
  },
  {
    id: "ratio_effectiveTaxRate",
    label: "Effective Tax Rate",
    statement: "ratios",
    property: "effectiveTaxRate",
    format: "percent",
  },
  {
    id: "ev_ebitda",
    label: "EV/EBITDA",
    statement: "ratios",
    property: "enterpriseValueMultiple",
    format: "number",
  },
  {
    id: "pe_ratio",
    label: "P/E Ratio",
    statement: "ratios",
    property: "priceToEarningsRatio",
    format: "number",
  },
  {
    id: "margin",
    label: "Net Profit Margin",
    statement: "ratios",
    property: "netProfitMargin",
    format: "percent",
  },
  {
    id: "fcf",
    label: "Free Cash Flow",
    statement: "cashflow",
    property: "freeCashFlow",
    format: "currency",
  },
];

export const STATEMENT_INDICATOR_INDEX: Record<string, number> = Object.fromEntries(
  STATEMENT_INDICATORS.map((item, index) => [item.id, index]),
);

export const STATEMENT_INDICATOR_BY_ID: Record<string, StatementIndicatorConfig> = Object.fromEntries(
  STATEMENT_INDICATORS.map((item) => [item.id, item]),
) as Record<string, StatementIndicatorConfig>;

export const STATEMENT_INDICATOR_BY_INDEX: Record<number, StatementIndicatorConfig> = Object.fromEntries(
  STATEMENT_INDICATORS.map((item, index) => [index, item]),
) as Record<number, StatementIndicatorConfig>;

export const STATEMENT_INDICATOR_TAB_MAP: Record<string, StatementIndicatorTab> = Object.fromEntries(
  STATEMENT_INDICATORS.map((item) => [item.id, item.statement]),
) as Record<string, StatementIndicatorTab>;